#!/bin/sh
# Nomad Bootstrap — cli1 (client)
# Generated by CI — DO NOT EDIT

set -e

# ---- Args ----
while [ $# -gt 0 ]; do
  case "$1" in
    --gossip-key) GOSSIP_KEY="$2"; shift 2 ;;
    --seed-addr)  SEED_ADDR="$2";  shift 2 ;;
    *) echo "Usage: $0 --gossip-key <key> --seed-addr <ip>"; exit 1 ;;
  esac
done
[ -z "$GOSSIP_KEY" ] && { echo "ERROR: --gossip-key required"; exit 1; }
[ -z "$SEED_ADDR" ]  && { echo "ERROR: --seed-addr required"; exit 1; }

echo "=== Nomad Bootstrap: cli1 (client) ==="

# ---- OS check ----
command -v pkg >/dev/null 2>&1 || { echo "ERROR: FreeBSD required"; exit 1; }
echo "✓ FreeBSD"

# ---- Install ----
if command -v nomad >/dev/null 2>&1; then
  echo "✓ Nomad: $(nomad version | head -1)"
else
  echo "→ pkg install nomad..."
  pkg install -y nomad
fi
mkdir -p /opt/nomad/data /etc/nomad.d

# ---- Config ----
cat > /etc/nomad.d/client.hcl << 'NMD'
datacenter = "dc1"
name       = "cli1"
data_dir   = "/opt/nomad"

client {
  enabled = true
  options { "driver.raw_exec.enable" = "1" }
  server_join { retry_join = ["SEED_ADDR_PLACEHOLDER:4648"] }
}

NMD

# ---- Inject key & addr ----
sed -i '' "s/GOSSIP_KEY_PLACEHOLDER/${GOSSIP_KEY}/" /etc/nomad.d/client.hcl
sed -i '' "s/SEED_ADDR_PLACEHOLDER:4648/${SEED_ADDR}:4648/" /etc/nomad.d/client.hcl

# ---- Start ----
sysrc nomad_enable=YES
sysrc nomad_args="-config=/etc/nomad.d"
service nomad status >/dev/null 2>&1 && service nomad restart || service nomad start

# ---- Wait ----
for i in $(seq 1 60); do
  nomad server members 2>/dev/null | grep -q alive && break
  sleep 1
done

echo "✓ cli1 ready"