# Nginx — Nomad API Reverse Proxy + CORS
# Generated by anvil CI — DO NOT EDIT

job "nginx" {
  datacenters = ["dc1"]
  type        = "service"

  group "proxy" {
    count = 1

    constraint {
      attribute = "${node.unique.name}"
      value     = "seed"
    }

    network {
      port "http" { static = 4647 }
    }

    task "nginx" {
      driver = "exec"

      config {
        command = "/usr/local/sbin/nginx"
        args = ["-c", "${NOMAD_TASK_DIR}/nginx.conf", "-g", "daemon off;"]
      }

      template {
        data = <<EOF
worker_processes 1;
error_log /dev/stderr;
pid ${NOMAD_TASK_DIR}/nginx.pid;

events { worker_connections 32; }

http {
  access_log off;

  server {
    listen ${NOMAD_PORT_http};

    # CORS — allow anvil SPA to call Nomad API
    set $cors "true";
    if ($http_origin ~* "https?://(localhost|127\.0\.0\.1|.*\.github\.io)") {
      set $cors "${http_origin}";
    }

    add_header Access-Control-Allow-Origin  $cors;
    add_header Access-Control-Allow-Methods "GET,POST,PUT,DELETE,OPTIONS";
    add_header Access-Control-Allow-Headers "Authorization,Content-Type,X-Nomad-Token";
    add_header Access-Control-Allow-Credentials "true";

    if ($request_method = OPTIONS) {
      return 204;
    }

    location / {
      proxy_pass http://127.0.0.1:4646;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass_request_headers on;
    }
  }
}
EOF
        destination = "local/nginx.conf"
      }

      resources {
        memory = 64
      }
    }
  }
}