#!/bin/sh
# Nomad Bootstrap — seed (seed server)
# OS: linux | Net: dhcp | BBR: true | TZ: Asia/Shanghai
# Generated by CI — DO NOT EDIT

set -e

# ================================================================
# 0. Args
# ================================================================
REINSTALL=0
GOSSIP_KEY=""
NODE_IP=""
while [ $# -gt 0 ]; do
  case "$1" in
    --gossip-key) GOSSIP_KEY="$2"; shift 2 ;;
    --ip)         NODE_IP="$2";    shift 2 ;;
    --reinstall)  REINSTALL=1; shift ;;
    *) echo "Usage: $0 --gossip-key <key> [--ip <addr>] [--reinstall]"; exit 1 ;;
  esac
done
[ -z "$GOSSIP_KEY" ] && { echo "ERROR: --gossip-key required"; exit 1; }

echo "=== Nomad Bootstrap: seed (seed) ==="

# ================================================================
# 1. OS Detect
# ================================================================
if [ -f /etc/os-release ]; then
  . /etc/os-release
  echo "✓ OS: $PRETTY_NAME"
  IS_LINUX=1
elif [ "$(uname -s)" = "FreeBSD" ]; then
  echo "✓ OS: FreeBSD $(freebsd-version)"
  IS_LINUX=0
else
  echo "ERROR: unsupported OS ($(uname -s))"
  exit 1
fi

# ================================================================
# 2. Hostname
# ================================================================
echo "→ Setting hostname: nomad-seed-01"
if [ "$IS_LINUX" = 1 ]; then
  hostnamectl set-hostname "nomad-seed-01" 2>/dev/null || hostname "nomad-seed-01"
else
  sysrc hostname="nomad-seed-01" 2>/dev/null || true
  hostname "nomad-seed-01"
fi
echo "✓ Hostname: $(hostname)"

# ================================================================
# 3. Timezone
# ================================================================
echo "→ Setting timezone: Asia/Shanghai"
if [ "$IS_LINUX" = 1 ]; then
  timedatectl set-timezone "Asia/Shanghai" 2>/dev/null || true
else
  tzsetup "Asia/Shanghai" 2>/dev/null || true
fi
echo "✓ Timezone: Asia/Shanghai"

# ================================================================
# 4. Network
# ================================================================
echo "✓ Network: DHCP (no static config)"

# ================================================================
# 5. BBR + Network Tuning
# ================================================================
echo "→ Enabling BBR..."
modprobe tcp_bbr 2>/dev/null || true
sysctl -w net.core.default_qdisc=fq 2>/dev/null || true
sysctl -w net.ipv4.tcp_congestion_control=bbr 2>/dev/null || true
CONG=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null) && echo "✓ TCP congestion: $CONG" || echo "⚠  BBR may not be available"

# ================================================================
# 6. System Tuning
# ================================================================
echo "→ Applying system tuning..."
sysctl -w vm.swappiness=1 2>/dev/null || true
sysctl -w vm.vfs_cache_pressure=50 2>/dev/null || true
sysctl -w net.core.somaxconn=65535 2>/dev/null || true
sysctl -w net.ipv4.tcp_max_syn_backlog=8192 2>/dev/null || true
sysctl -w net.ipv4.ip_local_port_range="1024 65535" 2>/dev/null || true
sysctl -w net.ipv4.tcp_tw_reuse=1 2>/dev/null || true
sysctl -w fs.file-max=2097152 2>/dev/null || true
# Persist
cat > /etc/sysctl.d/99-anvil.conf << 'EOF'
vm.swappiness=1
vm.vfs_cache_pressure=50
net.core.somaxconn=65535
net.ipv4.tcp_max_syn_backlog=8192
net.ipv4.ip_local_port_range=1024 65535
net.ipv4.tcp_tw_reuse=1
fs.file-max=2097152
EOF
echo "✓ System tuning applied"

# ================================================================
# 7. Reinstall (optional)
# ================================================================
if [ "$REINSTALL" = 1 ]; then
  echo "⚠  REINSTALL: stopping Nomad and purging data"
  if [ "$IS_LINUX" = 1 ]; then
    systemctl stop nomad 2>/dev/null || true
  else
    service nomad stop 2>/dev/null || true
  fi
  rm -rf /opt/nomad/data /etc/nomad.d
  echo "✓ Data purged"
fi

# ================================================================
# 8. Install Nomad
# ================================================================
if command -v nomad >/dev/null 2>&1; then
  echo "✓ Nomad: $(nomad version | head -1)"
else
  echo "→ Installing Nomad..."
  if [ "$IS_LINUX" = 1 ]; then
    NOMAD_VER="1.9.6"
    ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
    curl -fsSL "https://releases.hashicorp.com/nomad/${NOMAD_VER}/nomad_${NOMAD_VER}_linux_${ARCH}.zip" -o /tmp/nomad.zip
    unzip -o /tmp/nomad.zip -d /usr/local/bin/
    chmod +x /usr/local/bin/nomad
    rm -f /tmp/nomad.zip
  else
    pkg install -y nomad
  fi
  echo "✓ Nomad installed"
fi

mkdir -p /opt/nomad/data /etc/nomad.d

# ================================================================
# 9. Nomad Config
# ================================================================
cat > /etc/nomad.d/server.hcl << 'NMD'
datacenter = "dc1"
name       = "seed"
data_dir   = "/opt/nomad"

server {
  enabled          = true
  bootstrap_expect = 1
  encrypt          = "GOSSIP_KEY_PLACEHOLDER"
}

client {
  enabled = true
  options { "driver.raw_exec.enable" = "1" }
}

plugin "pot" { config { enabled = true } }
NMD

# ---- ACL ----
cat > /etc/nomad.d/acl.hcl << 'NMD'
acl { enabled = true }
NMD

# ---- Inject key ----
sed -i "s/GOSSIP_KEY_PLACEHOLDER/${GOSSIP_KEY}/" /etc/nomad.d/server.hcl

# ================================================================
# 10. Start Nomad
# ================================================================
if [ "$IS_LINUX" = 1 ]; then
  cat > /etc/systemd/system/nomad.service << 'UNIT'
[Unit]
Description=Nomad
After=network.target
[Service]
ExecStart=/usr/local/bin/nomad agent -config=/etc/nomad.d
Restart=on-failure
[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable nomad
  systemctl restart nomad || systemctl start nomad
else
  sysrc nomad_enable=YES
  sysrc nomad_args="-config=/etc/nomad.d"
  service nomad status >/dev/null 2>&1 && service nomad restart || service nomad start
fi

# ================================================================
# 11. Wait for Nomad + ACL Bootstrap
# ================================================================
echo "→ Waiting for Nomad..."
for i in $(seq 1 30); do
  nomad server members 2>/dev/null | grep -q alive && break
  sleep 1
done

echo "→ Bootstrapping ACL..."
MGMT_TOKEN=$(nomad acl bootstrap -json 2>/dev/null | grep -o '"SecretID":"[^"]*"' | head -1 | cut -d'"' -f4)
if [ -n "$MGMT_TOKEN" ]; then
  echo "✓ Management Token: $MGMT_TOKEN"
  echo "NOMAD MANAGEMENT TOKEN: $MGMT_TOKEN"
else
  echo "⚠  ACL may already be bootstrapped (or Nomad not ready)"
fi

# ================================================================
# 12. Deploy Jobs (Kanidm + Nginx)
# ================================================================
if [ -n "$MGMT_TOKEN" ]; then
  export NOMAD_TOKEN="$MGMT_TOKEN"
  export NOMAD_ADDR="http://127.0.0.1:4646"
  cat > /tmp/kanidm.hcl << 'KJOB'
# Kanidm — Identity Provider
# Generated by anvil CI — DO NOT EDIT

job "kanidm" {
  datacenters = ["dc1"]
  type        = "service"

  group "server" {
    count = 1

    constraint {
      attribute = "${node.unique.name}"
      value     = "seed"
    }

    network {
      port "https" { static = 8443 }
    }

    task "kanidm" {
      driver = "exec"

      config {
        command = "/usr/local/sbin/kanidmd"
        args = ["server", "-c", "${NOMAD_TASK_DIR}/server.toml"]
      }

      template {
        data = <<EOF
# Kanidm server config
# After first boot:
#   1. kanidmd recover-account admin
#   2. kanidm system oauth2 create ...
domain = "idm.local"
origin = "https://idm.local:8443"
bindaddress = "0.0.0.0:8443"
ldapbindaddress = "0.0.0.0:3636"
db_path = "${NOMAD_ALLOC_DIR}/kanidm.db"
tls_ca = "/opt/nomad/data/kanidm/ca.pem"
tls_cert = "/opt/nomad/data/kanidm/cert.pem"
tls_key = "/opt/nomad/data/kanidm/key.pem"
log_level = "info"
EOF
        destination = "local/server.toml"
      }

      resources {
        memory = 256
      }
    }
  }
}
  KJOB
  cat > /tmp/nginx.hcl << 'NJOB'
# Nginx — Nomad API Reverse Proxy + CORS
# Generated by anvil CI — DO NOT EDIT

job "nginx" {
  datacenters = ["dc1"]
  type        = "service"

  group "proxy" {
    count = 1

    constraint {
      attribute = "${node.unique.name}"
      value     = "seed"
    }

    network {
      port "http" { static = 4647 }
    }

    task "nginx" {
      driver = "exec"

      config {
        command = "/usr/local/sbin/nginx"
        args = ["-c", "${NOMAD_TASK_DIR}/nginx.conf", "-g", "daemon off;"]
      }

      template {
        data = <<EOF
worker_processes 1;
error_log /dev/stderr;
pid ${NOMAD_TASK_DIR}/nginx.pid;

events { worker_connections 32; }

http {
  access_log off;

  server {
    listen ${NOMAD_PORT_http};

    # CORS — allow anvil SPA to call Nomad API
    set $cors "true";
    if ($http_origin ~* "https?://(localhost|127\.0\.0\.1|.*\.github\.io)") {
      set $cors "${http_origin}";
    }

    add_header Access-Control-Allow-Origin  $cors;
    add_header Access-Control-Allow-Methods "GET,POST,PUT,DELETE,OPTIONS";
    add_header Access-Control-Allow-Headers "Authorization,Content-Type,X-Nomad-Token";
    add_header Access-Control-Allow-Credentials "true";

    if ($request_method = OPTIONS) {
      return 204;
    }

    location / {
      proxy_pass http://127.0.0.1:4646;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass_request_headers on;
    }
  }
}
EOF
        destination = "local/nginx.conf"
      }

      resources {
        memory = 64
      }
    }
  }
}
  NJOB
  echo "→ Submitting kanidm..."
  nomad job run /tmp/kanidm.hcl 2>/dev/null || echo "⚠  kanidm submit failed"
  echo "→ Submitting nginx..."
  nomad job run /tmp/nginx.hcl 2>/dev/null || echo "⚠  nginx submit failed"
  rm -f /tmp/kanidm.hcl /tmp/nginx.hcl
fi

echo "✓ Bootstrap complete — seed ready"