#!/bin/sh
# Nomad Bootstrap — seed (seed server)
# Generated by CI — DO NOT EDIT

set -e

# ---- Args ----
while [ $# -gt 0 ]; do
  case "$1" in
    --gossip-key) GOSSIP_KEY="$2"; shift 2 ;;
    *) echo "Usage: $0 --gossip-key <key>"; exit 1 ;;
  esac
done
[ -z "$GOSSIP_KEY" ] && { echo "ERROR: --gossip-key required"; exit 1; }

echo "=== Nomad Bootstrap: seed (seed) ==="

# ---- OS check ----
command -v pkg >/dev/null 2>&1 || { echo "ERROR: FreeBSD required"; exit 1; }
echo "✓ FreeBSD"

# ---- Install ----
if command -v nomad >/dev/null 2>&1; then
  echo "✓ Nomad: $(nomad version | head -1)"
else
  echo "→ pkg install nomad..."
  pkg install -y nomad
fi
pkg install -y nomad-pot-driver 2>/dev/null || true
pkg install -y nginx 2>/dev/null || true
mkdir -p /opt/nomad/data /etc/nomad.d

# ---- Config ----
cat > /etc/nomad.d/server.hcl << 'NMD'
datacenter = "dc1"
name       = "seed"
data_dir   = "/opt/nomad"

server {
  enabled          = true
  bootstrap_expect = 1
  encrypt          = "GOSSIP_KEY_PLACEHOLDER"
}

client {
  enabled = true
  options { "driver.raw_exec.enable" = "1" }
}

plugin "pot" { config { enabled = true } }
NMD

# ---- ACL ----
cat > /etc/nomad.d/acl.hcl << 'NMD'
acl { enabled = true }
NMD

# ---- Inject key ----
sed -i '' "s/GOSSIP_KEY_PLACEHOLDER/${GOSSIP_KEY}/" /etc/nomad.d/server.hcl

# ---- Start Nomad ----
sysrc nomad_enable=YES
sysrc nomad_args="-config=/etc/nomad.d"
service nomad status >/dev/null 2>&1 && service nomad restart || service nomad start

# ---- Wait for Nomad ----
echo "→ Waiting for Nomad..."
for i in $(seq 1 30); do
  nomad server members 2>/dev/null | grep -q alive && break
  sleep 1
done

# ---- ACL Bootstrap ----
echo "→ Bootstrapping ACL..."
MGMT_TOKEN=$(nomad acl bootstrap -json 2>/dev/null | grep -o '"SecretID":"[^"]*"' | head -1 | cut -d'"' -f4)
if [ -z "$MGMT_TOKEN" ]; then
  echo "WARNING: ACL bootstrap failed or already done"
  echo "  Retrieve token with: nomad acl token list"
  MGMT_TOKEN="<retrieve-manually>"
else
  echo "$MGMT_TOKEN" > /opt/nomad/mgmt-token
  chmod 600 /opt/nomad/mgmt-token
fi

# ---- Save Management Token ----
echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║  NOMAD MANAGEMENT TOKEN (save this!)            ║"
echo "╠══════════════════════════════════════════════════╣"
echo "║  $MGMT_TOKEN"
echo "╚══════════════════════════════════════════════════╝"
echo "  Stored at: /opt/nomad/mgmt-token"
echo ""

echo "✓ seed ready"

# ---- Phase 2: Deploy Kanidm + Nginx ----
echo ""
echo "=== Phase 2: Bootstrap Services ==="

# Write job files
cat > /tmp/kanidm.hcl << 'ANVIL_JOB'
# Kanidm — Identity Provider
# Generated by anvil CI — DO NOT EDIT

job "kanidm" {
  datacenters = ["dc1"]
  type        = "service"

  group "server" {
    count = 1

    constraint {
      attribute = "${node.unique.name}"
      value     = "seed"
    }

    network {
      port "https" { static = 8443 }
    }

    task "kanidm" {
      driver = "exec"

      config {
        command = "/usr/local/sbin/kanidmd"
        args = ["server", "-c", "${NOMAD_TASK_DIR}/server.toml"]
      }

      template {
        data = <<EOF
# Kanidm server config
# After first boot:
#   1. kanidmd recover-account admin
#   2. kanidm system oauth2 create ...
domain = "idm.local"
origin = "https://idm.local:8443"
bindaddress = "0.0.0.0:8443"
ldapbindaddress = "0.0.0.0:3636"
db_path = "${NOMAD_ALLOC_DIR}/kanidm.db"
tls_ca = "/opt/nomad/data/kanidm/ca.pem"
tls_cert = "/opt/nomad/data/kanidm/cert.pem"
tls_key = "/opt/nomad/data/kanidm/key.pem"
log_level = "info"
EOF
        destination = "local/server.toml"
      }

      resources {
        memory = 256
      }
    }
  }
}
ANVIL_JOB

cat > /tmp/nginx.hcl << 'ANVIL_JOB'
# Nginx — Nomad API Reverse Proxy + CORS
# Generated by anvil CI — DO NOT EDIT

job "nginx" {
  datacenters = ["dc1"]
  type        = "service"

  group "proxy" {
    count = 1

    constraint {
      attribute = "${node.unique.name}"
      value     = "seed"
    }

    network {
      port "http" { static = 4647 }
    }

    task "nginx" {
      driver = "exec"

      config {
        command = "/usr/local/sbin/nginx"
        args = ["-c", "${NOMAD_TASK_DIR}/nginx.conf", "-g", "daemon off;"]
      }

      template {
        data = <<EOF
worker_processes 1;
error_log /dev/stderr;
pid ${NOMAD_TASK_DIR}/nginx.pid;

events { worker_connections 32; }

http {
  access_log off;

  server {
    listen ${NOMAD_PORT_http};

    # CORS — allow anvil SPA to call Nomad API
    set $cors "true";
    if ($http_origin ~* "https?://(localhost|127\.0\.0\.1|.*\.github\.io)") {
      set $cors "${http_origin}";
    }

    add_header Access-Control-Allow-Origin  $cors;
    add_header Access-Control-Allow-Methods "GET,POST,PUT,DELETE,OPTIONS";
    add_header Access-Control-Allow-Headers "Authorization,Content-Type,X-Nomad-Token";
    add_header Access-Control-Allow-Credentials "true";

    if ($request_method = OPTIONS) {
      return 204;
    }

    location / {
      proxy_pass http://127.0.0.1:4646;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass_request_headers on;
    }
  }
}
EOF
        destination = "local/nginx.conf"
      }

      resources {
        memory = 64
      }
    }
  }
}
ANVIL_JOB

# Submit jobs
export NOMAD_TOKEN="$MGMT_TOKEN"
echo "→ Submitting kanidm..."
nomad job run /tmp/kanidm.hcl 2>&1 || echo "  WARN: kanidm submission failed (check logs)"
echo "→ Submitting nginx..."
nomad job run /tmp/nginx.hcl 2>&1 || echo "  WARN: nginx submission failed (check logs)"

# Wait for deployments
echo "→ Waiting for deployments..."
sleep 5
nomad job status kanidm 2>/dev/null || true
nomad job status nginx 2>/dev/null || true

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║  COLD START COMPLETE                            ║"
echo "╠══════════════════════════════════════════════════╣"
echo "║  Nomad API:  http://localhost:4646              ║"
echo "║  Nginx CORS: http://localhost:4647              ║"
echo "║  Kanidm:     https://localhost:8443             ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
echo "Next: configure Kanidm OIDC, then add worker nodes"