#!/bin/sh
# Nomad Bootstrap — srv2 (server)
# OS: linux | Net: static | BBR: true | TZ: Asia/Shanghai
# Generated by CI — DO NOT EDIT

set -e

# ================================================================
# 0. Args
# ================================================================
REINSTALL=0
GOSSIP_KEY=""
SEED_ADDR=""
NODE_IP=""
while [ $# -gt 0 ]; do
  case "$1" in
    --gossip-key) GOSSIP_KEY="$2"; shift 2 ;;
    --seed-addr)  SEED_ADDR="$2";  shift 2 ;;
    --ip)         NODE_IP="$2";    shift 2 ;;
    --reinstall)  REINSTALL=1; shift ;;
    *) echo "Usage: $0 --gossip-key <key> --seed-addr <ip> [--ip <addr>] [--reinstall]"; exit 1 ;;
  esac
done
[ -z "$GOSSIP_KEY" ] && { echo "ERROR: --gossip-key required"; exit 1; }
[ -z "$SEED_ADDR" ]  && { echo "ERROR: --seed-addr required"; exit 1; }

echo "=== Nomad Bootstrap: srv2 (server) ==="

# ================================================================
# 1. OS Detect
# ================================================================
if [ -f /etc/os-release ]; then
  . /etc/os-release
  echo "✓ OS: $PRETTY_NAME"
  IS_LINUX=1
elif [ "$(uname -s)" = "FreeBSD" ]; then
  echo "✓ OS: FreeBSD $(freebsd-version)"
  IS_LINUX=0
else
  echo "ERROR: unsupported OS ($(uname -s))"
  exit 1
fi

# ================================================================
# 2. Hostname
# ================================================================
echo "→ Setting hostname: nomad-srv-02"
if [ "$IS_LINUX" = 1 ]; then
  hostnamectl set-hostname "nomad-srv-02" 2>/dev/null || hostname "nomad-srv-02"
else
  sysrc hostname="nomad-srv-02" 2>/dev/null || true
  hostname "nomad-srv-02"
fi
echo "✓ Hostname: $(hostname)"

# ================================================================
# 3. Timezone
# ================================================================
echo "→ Setting timezone: Asia/Shanghai"
if [ "$IS_LINUX" = 1 ]; then
  timedatectl set-timezone "Asia/Shanghai" 2>/dev/null || true
else
  tzsetup "Asia/Shanghai" 2>/dev/null || true
fi
echo "✓ Timezone: Asia/Shanghai"

# ================================================================
# 4. Network
# ================================================================
echo "→ Setting static IP: NODE_IP_PLACEHOLDER"
IFACE=$(ip route | grep default | awk '{print $5}' | head -1)
[ -z "$IFACE" ] && { echo "WARN: cannot detect interface, skipping static IP"; } || {
  ip addr add NODE_IP_PLACEHOLDER/24 dev $IFACE 2>/dev/null || true
  ip route add default via NODE_IP_PLACEHOLDER 2>/dev/null || true
  echo "✓ Static IP: NODE_IP_PLACEHOLDER/24 on $IFACE"
}

# ================================================================
# 5. BBR + Network Tuning
# ================================================================
echo "→ Enabling BBR..."
modprobe tcp_bbr 2>/dev/null || true
sysctl -w net.core.default_qdisc=fq 2>/dev/null || true
sysctl -w net.ipv4.tcp_congestion_control=bbr 2>/dev/null || true
CONG=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null) && echo "✓ TCP congestion: $CONG" || echo "⚠  BBR may not be available"

# ================================================================
# 6. System Tuning
# ================================================================
echo "→ Applying system tuning..."
sysctl -w vm.swappiness=1 2>/dev/null || true
sysctl -w vm.vfs_cache_pressure=50 2>/dev/null || true
sysctl -w net.core.somaxconn=65535 2>/dev/null || true
sysctl -w net.ipv4.tcp_max_syn_backlog=8192 2>/dev/null || true
sysctl -w net.ipv4.ip_local_port_range="1024 65535" 2>/dev/null || true
sysctl -w net.ipv4.tcp_tw_reuse=1 2>/dev/null || true
sysctl -w fs.file-max=2097152 2>/dev/null || true
echo "✓ System tuning applied"

# ================================================================
# 7. Reinstall (optional)
# ================================================================
if [ "$REINSTALL" = 1 ]; then
  echo "⚠  REINSTALL: stopping Nomad and purging data"
  if [ "$IS_LINUX" = 1 ]; then
    systemctl stop nomad 2>/dev/null || true
  else
    service nomad stop 2>/dev/null || true
  fi
  rm -rf /opt/nomad/data /etc/nomad.d
  echo "✓ Data purged"
fi

# ================================================================
# 8. Install Nomad
# ================================================================
if command -v nomad >/dev/null 2>&1; then
  echo "✓ Nomad: $(nomad version | head -1)"
else
  echo "→ Installing Nomad..."
  if [ "$IS_LINUX" = 1 ]; then
    NOMAD_VER="1.9.6"
    ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
    curl -fsSL "https://releases.hashicorp.com/nomad/${NOMAD_VER}/nomad_${NOMAD_VER}_linux_${ARCH}.zip" -o /tmp/nomad.zip
    unzip -o /tmp/nomad.zip -d /usr/local/bin/
    chmod +x /usr/local/bin/nomad
    rm -f /tmp/nomad.zip
  else
    pkg install -y nomad
  fi
  echo "✓ Nomad installed"
fi

mkdir -p /opt/nomad/data /etc/nomad.d

# ================================================================
# 9. Nomad Config
# ================================================================
cat > /etc/nomad.d/server.hcl << 'NMD'
datacenter = "dc1"
name       = "srv2"
data_dir   = "/opt/nomad"

server {
  enabled    = true
  retry_join = ["SEED_ADDR_PLACEHOLDER:4648"]
  encrypt    = "GOSSIP_KEY_PLACEHOLDER"
}
NMD

# ---- Inject key & addr ----
sed -i "s/GOSSIP_KEY_PLACEHOLDER/${GOSSIP_KEY}/" /etc/nomad.d/server.hcl
sed -i "s/SEED_ADDR_PLACEHOLDER:4648/${SEED_ADDR}:4648/" /etc/nomad.d/server.hcl

# ================================================================
# 10. Start Nomad
# ================================================================
if [ "$IS_LINUX" = 1 ]; then
  cat > /etc/systemd/system/nomad.service << 'UNIT'
[Unit]
Description=Nomad
After=network.target
[Service]
ExecStart=/usr/local/bin/nomad agent -config=/etc/nomad.d
Restart=on-failure
[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable nomad
  systemctl restart nomad || systemctl start nomad
else
  sysrc nomad_enable=YES
  sysrc nomad_args="-config=/etc/nomad.d"
  service nomad status >/dev/null 2>&1 && service nomad restart || service nomad start
fi

# ================================================================
# 11. Wait & Verify
# ================================================================
echo "→ Waiting for Nomad..."
for i in $(seq 1 60); do
  nomad server members 2>/dev/null | grep -q alive && break
  sleep 1
done

echo "✓ srv2 ready"