// gen-server.mjs — Seed server: bare metal → Nomad online
// Template system: {NAME} {DC} {HN} etc → JS replaces at generate time
// {D} → literal $ for shell variables

import { generate as genKanidm } from './gen-kanidm.mjs';
import { generate as genNginx  } from './gen-nginx.mjs';

const $ = String.fromCharCode(36);

const SCRIPT = `#!/usr/bin/env bash
# ============================================================================
#  Nomad Bootstrap — {NAME} (seed server)
#  OS: {OS}  Net: {NET}  BBR: {BBR}  TZ: {TZ}
#  Generated by anvil CI — DO NOT EDIT
# ============================================================================
#
#  Usage:  curl .../{NAME}.sh | bash -s -- --gossip-key <key> [flags]
#  Flags:  --auto  --reinstall  --nomad-ver <x.y.z>
#          --skip-hostname  --skip-tz  --skip-net  --skip-bbr  --skip-tune
#          --skip-ssh  --skip-firewall  --skip-update  --skip-jobs
#  Env:    NOMAD_VER  NODE_HOSTNAME  NODE_TZ  NODE_IP
# ============================================================================

set -euo pipefail

:{D}{NOMAD_VER:=1.9.6}
:{D}{NODE_HOSTNAME:={HN}}
:{D}{NODE_TZ:=UTC}
:{D}{NODE_IP:={NIP}}

AUTO=0; REINSTALL=0; GOSSIP_KEY=""
SKIP_HOSTNAME=0; SKIP_TZ=0; SKIP_NET=0; SKIP_BBR=0; SKIP_TUNE=0
SKIP_SSH=0; SKIP_FIREWALL=0; SKIP_UPDATE=0; SKIP_JOBS=0
while [[ $# -gt 0 ]]; do
  case "{D}1" in
    --gossip-key)   GOSSIP_KEY="{D}2"; shift 2 ;;
    --auto)         AUTO=1; shift ;;
    --reinstall)    REINSTALL=1; shift ;;
    --nomad-ver)    NOMAD_VER="{D}2"; shift 2 ;;
    --skip-hostname) SKIP_HOSTNAME=1; shift ;;
    --skip-tz)       SKIP_TZ=1; shift ;;
    --skip-net)      SKIP_NET=1; shift ;;
    --skip-bbr)      SKIP_BBR=1; shift ;;
    --skip-tune)     SKIP_TUNE=1; shift ;;
    --skip-ssh)      SKIP_SSH=1; shift ;;
    --skip-firewall) SKIP_FIREWALL=1; shift ;;
    --skip-update)   SKIP_UPDATE=1; shift ;;
    --skip-jobs)     SKIP_JOBS=1; shift ;;
    -h|--help) sed -n '3,/^$/p' "{D}0" | head -20; exit 0 ;;
    *) echo "Unknown: {D}1  (try --help)"; exit 1 ;;
  esac
done
[[ -z "{D}GOSSIP_KEY" ]] && { echo "ERROR: --gossip-key required"; exit 1; }

# ---- Color helpers ----
RED='\\033[31m'; GREEN='\\033[32m'; YELLOW='\\033[33m'
CYAN='\\033[36m'; BOLD='\\033[1m'; RST='\\033[0m'; STEP=0
log()   { printf "  %s\\n" "{D}*"; }
ok()    { printf "{D}{GREEN}✓{D}{RST} %s\\n" "{D}*"; }
warn()  { printf "{D}{YELLOW}⚠{D}{RST} %s\\n" "{D}*" >&2; }
fail()  { printf "{D}{RED}✗{D}{RST} %s\\n" "{D}*" >&2; }
banner(){ printf "\\n{D}{CYAN}{D}{BOLD}── Step %s/{D}{TOTAL:-?}: %s{D}{RST}\\n" "$((++STEP))" "{D}*"; }
TOTAL=13
confirm() {
  [[ {D}AUTO -eq 1 ]] && return 0
  read -r -p "      {D}{1:-Continue? [Y/n]} " ans
  [[ "{D}ans" =~ ^[Nn] ]] && return 1
  return 0
}
trap 'fail "Bootstrap failed at line {D}LINENO"; exit 1' ERR

# ==================================================================
#  1. OS Detect
# ==================================================================
banner "OS Detect"
if [[ -f /etc/os-release ]]; then
  . /etc/os-release; ok "OS: {D}PRETTY_NAME"; IS_LINUX=1
  if command -v apt-get &>/dev/null; then PKG_MGR="apt-get"
  elif command -v dnf &>/dev/null; then PKG_MGR="dnf"
  elif command -v yum &>/dev/null; then PKG_MGR="yum"
  elif command -v apk &>/dev/null; then PKG_MGR="apk"
  else warn "no known package manager"; fi
elif [[ "{D}(uname -s)" == "FreeBSD" ]]; then
  ok "OS: FreeBSD {D}(freebsd-version 2>/dev/null || uname -r)"; IS_LINUX=0; PKG_MGR="pkg"
else fail "unsupported OS: {D}(uname -s)"; exit 1
fi

# ==================================================================
#  2. System Update
# ==================================================================
banner "System Update"
if [[ {D}SKIP_UPDATE -eq 1 ]]; then warn "skipped (--skip-update)"
elif confirm "Update system packages? [Y/n]"; then
  if [[ {D}IS_LINUX -eq 1 ]]; then
    case "{D}PKG_MGR" in
      apt-get) apt-get update -qq && apt-get upgrade -y -qq ;;
      dnf|yum) {D}PKG_MGR update -y -q ;;
      apk)     apk update && apk upgrade ;;
    esac
  else pkg update -q && pkg upgrade -y -q; fi
  ok "packages updated"
else warn "update skipped by user"; fi

# ==================================================================
#  3. Hostname
# ==================================================================
banner "Hostname"
if [[ {D}SKIP_HOSTNAME -eq 1 ]]; then warn "skipped (--skip-hostname)"
else
  if [[ {D}AUTO -eq 0 ]]; then
    read -r -p "      Hostname [{D}NODE_HOSTNAME]: " input
    [[ -n "{D}input" ]] && NODE_HOSTNAME="{D}input"
  fi
  log "setting: {D}NODE_HOSTNAME"
  if [[ {D}IS_LINUX -eq 1 ]]; then
    hostnamectl set-hostname "{D}NODE_HOSTNAME" 2>/dev/null || hostname "{D}NODE_HOSTNAME"
  else sysrc hostname="{D}NODE_HOSTNAME" 2>/dev/null || true; hostname "{D}NODE_HOSTNAME"; fi
  ok "{D}(hostname)"
fi

# ==================================================================
#  4. Timezone — UTC enforced for cluster time consistency
# ==================================================================
banner "Timezone & NTP (chrony)"
if [[ {D}SKIP_TZ -eq 1 ]]; then warn "skipped (--skip-tz)"
else
  log "setting timezone: UTC (cluster standard)"
  if [[ {D}IS_LINUX -eq 1 ]]; then timedatectl set-timezone UTC 2>/dev/null || true
  else tzsetup UTC 2>/dev/null || true; fi
  ok "Timezone: UTC"

  # ── chrony (modern NTP, faster sync than ntpd) ──
  log "installing chrony..."
  if [[ {D}IS_LINUX -eq 1 ]]; then
    if command -v apt-get >/dev/null 2>&1; then {D}SUDO apt-get install -y chrony >/dev/null 2>&1 || warn "chrony apt failed"
    elif command -v dnf >/dev/null 2>&1; then {D}SUDO dnf install -y chrony >/dev/null 2>&1 || warn "chrony dnf failed"
    elif command -v yum >/dev/null 2>&1; then {D}SUDO yum install -y chrony >/dev/null 2>&1 || warn "chrony yum failed"
    fi
    # Minimal chrony.conf — NTS preferred, pool fallback
    cat > /etc/chrony/chrony.conf <<'EOF'
server time.cloudflare.com iburst nts
server nts.netnod.se      iburst nts
pool   2.pool.ntp.org     iburst maxsources 2
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
rtconutc
port 0
EOF
    {D}SUDO systemctl enable chrony 2>/dev/null || {D}SUDO systemctl enable chronyd 2>/dev/null || true
    {D}SUDO systemctl restart chrony 2>/dev/null || {D}SUDO systemctl restart chronyd 2>/dev/null || true
    timedatectl set-ntp true 2>/dev/null || true
    # Verify sync
    sleep 2
    chronyc tracking 2>/dev/null | grep -q "Reference ID" && ok "chrony NTP synced" || warn "chrony may still be syncing"
  else
    # FreeBSD: chrony from pkg
    pkg install -y chrony >/dev/null 2>&1 || warn "chrony pkg failed"
    cat > /usr/local/etc/chrony.conf <<'EOF'
server time.cloudflare.com iburst nts
server nts.netnod.se      iburst nts
pool   2.pool.ntp.org     iburst maxsources 2
driftfile /var/db/chrony/drift
makestep 1.0 3
rtcsync
rtconutc
port 0
EOF
    sysrc chronyd_enable=YES 2>/dev/null || true
    service chronyd restart 2>/dev/null || true
    sleep 2
    chronyc tracking 2>/dev/null | grep -q "Reference ID" && ok "chrony NTP synced" || warn "chrony may still be syncing"
  fi
  ok "chrony NTP synced"
fi

# ==================================================================
#  5. Network
# ==================================================================
banner "Network"
if [[ {D}SKIP_NET -eq 1 ]]; then warn "skipped (--skip-net)"
#NETHERE#
fi

# ==================================================================
#  6. DNS
# ==================================================================
banner "DNS"
if [[ {D}SKIP_NET -eq 1 ]]; then warn "skipped (--skip-net)"
else
  if [[ {D}IS_LINUX -eq 1 ]]; then
    if ! grep -q "nameserver" /etc/resolv.conf 2>/dev/null; then
      echo "nameserver 1.1.1.1" >> /etc/resolv.conf
      echo "nameserver 8.8.8.8" >> /etc/resolv.conf
      ok "DNS fallback: 1.1.1.1, 8.8.8.8"
    else ok "DNS: {D}(grep nameserver /etc/resolv.conf | head -1)"; fi
  else ok "DNS: {D}(grep nameserver /etc/resolv.conf 2>/dev/null | head -1 || echo default)"; fi
fi

# ==================================================================
#  7. BBR
# ==================================================================
banner "BBR Congestion Control"
if [[ {D}SKIP_BBR -eq 1 ]]; then warn "skipped (--skip-bbr)"
elif confirm "Enable TCP BBR? [Y/n]"; then
  if [[ {D}IS_LINUX -eq 1 ]]; then
    modprobe tcp_bbr 2>/dev/null || true
    sysctl -w net.core.default_qdisc=fq 2>/dev/null || true
    sysctl -w net.ipv4.tcp_congestion_control=bbr 2>/dev/null || true
    echo "net.core.default_qdisc=fq" > /etc/sysctl.d/90-bbr.conf
    echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.d/90-bbr.conf
    local cc; cc={D}(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null) && ok "{D}cc" || warn "BBR unavailable"
  else kldload tcp_bbr 2>/dev/null || true
    sysctl net.inet.tcp.cc.algorithm=bbr 2>/dev/null && ok "BBR" || warn "BBR unavailable"; fi
else warn "BBR skipped by user"; fi

# ==================================================================
#  8. System Tuning
# ==================================================================
banner "System Tuning"
if [[ {D}SKIP_TUNE -eq 1 ]]; then warn "skipped (--skip-tune)"
elif confirm "Apply system tuning (sysctl)? [Y/n]"; then
  if [[ {D}IS_LINUX -eq 1 ]]; then
    sysctl -w vm.swappiness=1 2>/dev/null || true
    sysctl -w vm.vfs_cache_pressure=50 2>/dev/null || true
    sysctl -w net.core.somaxconn=65535 2>/dev/null || true
    sysctl -w net.ipv4.tcp_max_syn_backlog=8192 2>/dev/null || true
    sysctl -w net.ipv4.ip_local_port_range="1024 65535" 2>/dev/null || true
    sysctl -w net.ipv4.tcp_tw_reuse=1 2>/dev/null || true
    sysctl -w fs.file-max=2097152 2>/dev/null || true
    cat > /etc/sysctl.d/99-anvil.conf << 'EOF'
vm.swappiness=1
vm.vfs_cache_pressure=50
net.core.somaxconn=65535
net.ipv4.tcp_max_syn_backlog=8192
net.ipv4.ip_local_port_range=1024 65535
net.ipv4.tcp_tw_reuse=1
fs.file-max=2097152
EOF
  else sysctl kern.maxfiles=2097152 2>/dev/null || true
    sysctl net.inet.tcp.syncache.hashsize=1024 2>/dev/null || true
    echo "kern.maxfiles=2097152" >> /etc/sysctl.conf; fi
  ok "system tuning applied"
else warn "tuning skipped by user"; fi

# ==================================================================
#  9. SSH Hardening
# ==================================================================
banner "SSH Hardening"
if [[ {D}SKIP_SSH -eq 1 ]]; then warn "skipped (--skip-ssh)"
elif confirm "Apply SSH hardening? [Y/n]"; then
  SSHD_CFG=/etc/ssh/sshd_config
  cp "{D}SSHD_CFG" "{D}SSHD_CFG.bak.{D}(date +%s)" 2>/dev/null || true

  # Store custom conf in a drop-in directory when supported
  if grep -q "^Include" "{D}SSHD_CFG" 2>/dev/null && [[ -d /etc/ssh/sshd_config.d ]]; then
    SSHD_CFG=/etc/ssh/sshd_config.d/99-anvil.conf
  fi

  # ── AddressFamily auto-detect ──
  AF="any"
  if [[ "{D}{HAS_IPV6}" != "true" && "{D}{HAS_IPV4}" == "true" ]]; then AF="inet"
  elif [[ "{D}{HAS_IPV6}" == "true" && "{D}{HAS_IPV4}" != "true" ]]; then AF="inet6"
  fi

  # ── Port ──
  SSH_PORT="{D}{SSH_PORT:-22}"

  # ── HostKey optimization: ed25519 preferred, rsa fallback ──
  cat >> "{D}SSHD_CFG" << 'EOF'
# ── anvil SSH hardening ──
Port {D}SSH_PORT
AddressFamily {D}AF
Protocol 2
PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes
PermitEmptyPasswords no
X11Forwarding no
MaxAuthTries 3
ClientAliveInterval 300
ClientAliveCountMax 2
# Preferred host keys (ed25519 is fastest + most secure)
HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/ssh_host_rsa_key
EOF

  # Cleanup unused host key types (dsa, ecdsa)
  {D}SUDO rm -f /etc/ssh/ssh_host_dsa_key* /etc/ssh/ssh_host_ecdsa_key* 2>/dev/null || true

  # Validate & reload (FreeBSD uses service, Linux uses systemctl)
  if sshd -t 2>/dev/null; then
    if [[ {D}IS_LINUX -eq 1 ]]; then
      if systemctl is-active sshd >/dev/null 2>&1; then systemctl reload sshd 2>/dev/null || true
      else systemctl restart sshd 2>/dev/null || true; fi
    else
      service sshd reload 2>/dev/null || service sshd restart 2>/dev/null || true
    fi
    ok "SSH hardened (port {D}SSH_PORT, addr-family {D}AF)"
  else
    warn "SSH config invalid — restoring backup"
    cp "{D}SSHD_CFG.bak."* "{D}SSHD_CFG" 2>/dev/null || true; ls -t {D}SSHD_CFG.bak.* | head -1 | xargs cp -t "$(dirname {D}SSHD_CFG)"/ 2>/dev/null || true
  fi
else warn "SSH hardening skipped"; fi

# ==================================================================
#  10. Firewall
# ==================================================================
banner "Firewall"
if [[ {D}SKIP_FIREWALL -eq 1 ]]; then warn "skipped (--skip-firewall)"
elif confirm "Configure basic firewall? [Y/n]"; then
  if [[ {D}IS_LINUX -eq 1 ]]; then
    if command -v nft &>/dev/null; then
      nft add table inet anvil 2>/dev/null || true
      nft add chain inet anvil input '{ type filter hook input priority 0; }' 2>/dev/null || true
      nft add rule inet anvil input ct state established,related accept 2>/dev/null || true
      nft add rule inet anvil input iif lo accept 2>/dev/null || true
      nft add rule inet anvil input tcp dport 22 accept 2>/dev/null || true
      nft add rule inet anvil input tcp dport '{4646,4647,4648}' accept 2>/dev/null || true
      nft add rule inet anvil input tcp dport 443 accept 2>/dev/null || true
      nft add rule inet anvil input tcp dport 80 accept 2>/dev/null || true
      nft add rule inet anvil input drop 2>/dev/null || true
      nft list ruleset > /etc/nftables.conf 2>/dev/null || true
      ok "nftables: SSH, Nomad(4646-8), 80, 443"
    else warn "nftables not available, skipping"; fi
  else
    cat > /tmp/anvil_pf.conf << 'EOPF'
block all
pass in on lo0
pass out all keep state
pass in proto tcp to any port {22,4646,4647,4648,80,443}
EOPF
    pfctl -f /tmp/anvil_pf.conf 2>/dev/null && ok "pf enabled" || warn "pf failed"
  fi
else warn "firewall skipped"; fi

# ==================================================================
#  11. Reinstall
# ==================================================================
if [[ {D}REINSTALL -eq 1 ]]; then
  banner "Reinstall"
  if confirm "⚠  This will DESTROY existing Nomad data. Continue? [y/N]"; then
    if [[ {D}IS_LINUX -eq 1 ]]; then systemctl stop nomad 2>/dev/null || true
    else service nomad stop 2>/dev/null || true; fi
    rm -rf /opt/nomad/data /etc/nomad.d
    ok "data purged"
  else warn "reinstall cancelled"; exit 0; fi
fi

# ==================================================================
#  12. Install Nomad
# ==================================================================
banner "Install Nomad"
if command -v nomad &>/dev/null && [[ {D}REINSTALL -ne 1 ]]; then
  ok "Nomad: {D}(nomad version | head -1)"
else
  log "installing Nomad v{D}NOMAD_VER ..."
  if [[ {D}IS_LINUX -eq 1 ]]; then
    local arch; arch={D}(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
    local url="https://releases.hashicorp.com/nomad/{D}NOMAD_VER/nomad_{D}NOMAD_VER_linux_{D}arch.zip"
    curl -fsSL "{D}url" -o /tmp/nomad.zip
    unzip -o /tmp/nomad.zip -d /usr/local/bin/
    chmod +x /usr/local/bin/nomad
    rm -f /tmp/nomad.zip
  else pkg install -y nomad; fi
  ok "Nomad {D}(nomad version | head -1)"
fi
mkdir -p /opt/nomad/data /etc/nomad.d

# ==================================================================
#  13. Nomad Config + Start + ACL + Jobs
# ==================================================================
banner "Nomad Config"
cat > /etc/nomad.d/server.hcl << 'NMD'
datacenter = "{DC}"
name       = "{NAME}"
data_dir   = "/opt/nomad"

server {
  enabled          = true
  bootstrap_expect = 1
  encrypt          = "GOSSIP_KEY_PLACEHOLDER"
}

client {
  enabled = true
  options { "driver.raw_exec.enable" = "1" }
  host_volume "kanidm" {
    path      = "/opt/nomad/volumes/kanidm"
    read_only = false
  }
}
NMD

cat > /etc/nomad.d/acl.hcl << 'NMD'
acl { enabled = true }
NMD

sed -i "s/GOSSIP_KEY_PLACEHOLDER/{D}GOSSIP_KEY/" /etc/nomad.d/server.hcl
ok "config written"

banner "Start Nomad"
if [[ {D}IS_LINUX -eq 1 ]]; then
  cat > /etc/systemd/system/nomad.service << 'UNIT'
[Unit]
Description=Nomad
After=network.target
[Service]
Type=simple
ExecStart=/usr/local/bin/nomad agent -config=/etc/nomad.d
Restart=on-failure
RestartSec=5
LimitNOFILE=65536
[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload && systemctl enable nomad
  systemctl restart nomad 2>/dev/null || systemctl start nomad
else
  sysrc nomad_enable=YES
  sysrc nomad_args="-config=/etc/nomad.d"
  service nomad restart 2>/dev/null || service nomad start
fi

echo -n "→ Waiting for Nomad "
for i in {D}(seq 1 30); do echo -n "."; nomad server members 2>/dev/null | grep -q alive && break; sleep 1; done
echo ""; ok "Nomad running"

echo "→ Bootstrapping ACL..."
MGMT_TOKEN={D}(nomad acl bootstrap -json 2>/dev/null | grep -o '"SecretID":"[^"]*"' | head -1 | cut -d'"' -f4)
if [[ -n "{D}MGMT_TOKEN" ]]; then
  echo ""
  echo "╔══════════════════════════════════════════╗"
  echo "║  NOMAD MANAGEMENT TOKEN                  ║"
  printf "║  %-40s ║\\n" "{D}MGMT_TOKEN"
  echo "╚══════════════════════════════════════════╝"
  echo ""
else warn "ACL may already be bootstrapped — check existing tokens"; fi

if [[ {D}SKIP_JOBS -eq 1 ]]; then warn "Jobs skipped (--skip-jobs)"
elif [[ -n "{D}{MGMT_TOKEN:-}" ]]; then
  banner "Deploy Jobs"
  mkdir -p /opt/nomad/volumes/kanidm
  export NOMAD_TOKEN="{D}MGMT_TOKEN" NOMAD_ADDR="http://127.0.0.1:4646"
#KANIDM#
#NGINX#
  nomad job run /tmp/kanidm.hcl 2>/dev/null && ok "kanidm" || warn "kanidm failed"
  nomad job run /tmp/nginx.hcl  2>/dev/null && ok "nginx"  || warn "nginx failed"
  rm -f /tmp/kanidm.hcl /tmp/nginx.hcl
fi

echo ""
echo "╔══════════════════════════════════════════╗"
printf "║  %-40s ║\\n" "✓ Bootstrap complete"
printf "║  %-40s ║\\n" "{NAME} ready"
echo "╚══════════════════════════════════════════╝"`;

// ---- Export ----

export function generate(node, cluster) {
  const net = node.network || 'dhcp';
  const isLinux = (node.os || 'linux') === 'linux';
  const nip = node.ip || 'NODE_IP_PLACEHOLDER';

  // Build network block
  let netBlock;
  if (net !== 'static') {
    netBlock = '  ok "DHCP — using existing configuration"';
  } else if (isLinux) {
    const gw = nip.replace(/\.\d+$/, '.1');
    netBlock = `  IFACE=\$(\$(ip -o link show | awk -F': ' '/state UP/ && !/lo/{print $2; exit}'))
  if [[ -n "{D}IFACE" ]]; then
    if [[ {D}AUTO -eq 0 ]]; then read -r -p "      IP/CIDR [{D}NODE_IP/24]: " input; [[ -n "{D}input" ]] && NODE_IP="{D}input"; fi
    ip addr add {D}NODE_IP/24 dev {D}IFACE 2>/dev/null || true
    ip route add default via ${gw} 2>/dev/null || true
    ok "{D}NODE_IP/24 on {D}IFACE"
  else warn "no active UP interface found"; fi`;
  } else {
    netBlock = `  IFACE=\$(\$(ifconfig -l ether 2>/dev/null | awk '{print $1}'))
  if [[ -n "{D}IFACE" ]]; then
    if [[ {D}AUTO -eq 0 ]]; then read -r -p "      IP [{D}NODE_IP]: " input; [[ -n "{D}input" ]] && NODE_IP="{D}input"; fi
    sysrc ifconfig_{D}IFACE="inet {D}NODE_IP netmask 255.255.255.0"
    sysrc defaultrouter="{D}(echo {D}NODE_IP | sed 's/.[0-9]*$/.1/')"
    service netif restart 2>/dev/null || true
    ok "{D}NODE_IP/24 on {D}IFACE"; fi`;
  }

  let out = SCRIPT.replace('#NETHERE#', netBlock);

  // Inject Kanidm + Nginx
  const kanidmHcl = genKanidm(cluster, node);
  const nginxHcl  = genNginx(cluster, node);
  out = out.replace('#KANIDM#', `cat > /tmp/kanidm.hcl << 'KJOB'\n${kanidmHcl}\nKJOB`);
  out = out.replace('#NGINX#',  `cat > /tmp/nginx.hcl << 'NJOB'\n${nginxHcl}\nNJOB`);

  // Substitute template vars
  const dc = cluster?.datacenter || 'dc1';
  return out
    .replace(/\{NAME\}/g, node.name)
    .replace(/\{DC\}/g, dc)
    .replace(/\{HN\}/g, node.hostname || node.name)
    .replace(/\{TZ\}/g, 'UTC')
    .replace(/\{OS\}/g, node.os || 'linux')
    .replace(/\{NET\}/g, net)
    .replace(/\{BBR\}/g, node.bbr !== false ? 'true' : 'false')
    .replace(/\{NIP\}/g, nip)
    .replace(/\{D\}/g, $);
}
