// scripts/lib/gen-kanidm.mjs
// 职责：生成 Kanidm 身份中心 Nomad job HCL
// 输入：cluster{}, seed{}
// 输出：kanidm.hcl 文本

export function generate(cluster, seed) {
  const dc = cluster?.datacenter || 'dc1';
  return _lines([
    `# Kanidm — Identity Provider`,
    `# Generated by anvil CI — DO NOT EDIT`,
    ``,
    `job "kanidm" {`,
    `  datacenters = ["${dc}"]`,
    `  type        = "service"`,
    ``,
    `  group "server" {`,
    `    count = 1`,
    ``,
    `    constraint {`,
    `      attribute = "\${node.unique.name}"`,
    `      value     = "${seed.name}"`,
    `    }`,
    ``,
    `    network {`,
    `      port "https" { static = 8443 }`,
    `    }`,
    ``,
    `    task "kanidm" {`,
    `      driver = "exec"`,
    ``,
    `      config {`,
    `        command = "/usr/local/sbin/kanidmd"`,
    `        args = ["server", "-c", "\${NOMAD_TASK_DIR}/server.toml"]`,
    `      }`,
    ``,
    `      template {`,
    `        data = <<EOF`,
    `# Kanidm server config`,
    `# After first boot:`,
    `#   1. kanidmd recover-account admin`,
    `#   2. kanidm system oauth2 create ...`,
    `domain = "idm.local"`,
    `origin = "https://idm.local:8443"`,
    `bindaddress = "0.0.0.0:8443"`,
    `ldapbindaddress = "0.0.0.0:3636"`,
    `db_path = "\${NOMAD_ALLOC_DIR}/kanidm.db"`,
    `tls_ca = "/opt/nomad/data/kanidm/ca.pem"`,
    `tls_cert = "/opt/nomad/data/kanidm/cert.pem"`,
    `tls_key = "/opt/nomad/data/kanidm/key.pem"`,
    `log_level = "info"`,
    `EOF`,
    `        destination = "local/server.toml"`,
    `      }`,
    ``,
    `      resources {`,
    `        memory = 256`,
    `      }`,
    `    }`,
    `  }`,
    `}`,
  ]);
}

function _lines(a) { return a.join('\n'); }
