// scripts/lib/gen-server.mjs
// 职责：种子 Server ← 裸机 → Nomad 在线
// 输入：node{name,ip,role,hostname?,timezone?,os?,bbr?,network?}, cluster{}
// 输出：Shell 脚本（Linux + FreeBSD 双支持）

import { generate as genKanidm } from './gen-kanidm.mjs';
import { generate as genNginx  } from './gen-nginx.mjs';

export function generate(node, cluster) {
  const dc    = cluster?.datacenter || 'dc1';
  const os    = node.os || 'linux';
  const hname = node.hostname || node.name;
  const tz    = node.timezone || 'UTC';
  const bbr   = node.bbr !== false;           // default true
  const net   = node.network || 'dhcp';       // dhcp | static
  const nip   = node.ip || 'NODE_IP_PLACEHOLDER';

  const isLinux   = os === 'linux';
  const isFreeBSD = os === 'freebsd';
  const isStatic  = net === 'static';

  const kanidmHcl = genKanidm(cluster, node);
  const nginxHcl  = genNginx(cluster, node);

  return _lines([
    '#!/bin/sh',
    `# Nomad Bootstrap — ${node.name} (seed server)`,
    `# OS: ${os} | Net: ${net} | BBR: ${bbr} | TZ: ${tz}`,
    '# Generated by CI — DO NOT EDIT',
    '',
    'set -e',
    '',
    '# ================================================================',
    '# 0. Args',
    '# ================================================================',
    'REINSTALL=0',
    'GOSSIP_KEY=""',
    'NODE_IP=""',
    'while [ $# -gt 0 ]; do',
    '  case "$1" in',
    '    --gossip-key) GOSSIP_KEY="$2"; shift 2 ;;',
    '    --ip)         NODE_IP="$2";    shift 2 ;;',
    '    --reinstall)  REINSTALL=1; shift ;;',
    '    *) echo "Usage: $0 --gossip-key <key> [--ip <addr>] [--reinstall]"; exit 1 ;;',
    '  esac',
    'done',
    '[ -z "$GOSSIP_KEY" ] && { echo "ERROR: --gossip-key required"; exit 1; }',
    '',
    `echo "=== Nomad Bootstrap: ${node.name} (seed) ==="`,
    '',
    '# ================================================================',
    '# 1. OS Detect',
    '# ================================================================',
    'if [ -f /etc/os-release ]; then',
    '  . /etc/os-release',
    '  echo "✓ OS: $PRETTY_NAME"',
    `  IS_LINUX=1`,
    'elif [ "$(uname -s)" = "FreeBSD" ]; then',
    '  echo "✓ OS: FreeBSD $(freebsd-version)"',
    `  IS_LINUX=0`,
    'else',
    '  echo "ERROR: unsupported OS ($(uname -s))"',
    '  exit 1',
    'fi',
    '',
    '# ================================================================',
    '# 2. Hostname',
    '# ================================================================',
    `echo "→ Setting hostname: ${hname}"`,
    `if [ "$IS_LINUX" = 1 ]; then`,
    `  hostnamectl set-hostname "${hname}" 2>/dev/null || hostname "${hname}"`,
    `else`,
    `  sysrc hostname="${hname}" 2>/dev/null || true`,
    `  hostname "${hname}"`,
    `fi`,
    `echo "✓ Hostname: $(hostname)"`,
    '',
    '# ================================================================',
    '# 3. Timezone',
    '# ================================================================',
    `echo "→ Setting timezone: ${tz}"`,
    `if [ "$IS_LINUX" = 1 ]; then`,
    `  timedatectl set-timezone "${tz}" 2>/dev/null || true`,
    `else`,
    `  tzsetup "${tz}" 2>/dev/null || true`,
    `fi`,
    `echo "✓ Timezone: ${tz}"`,
    '',
    '# ================================================================',
    '# 4. Network',
    '# ================================================================',
    ..._netSetup(isLinux, isStatic, nip),
    '',
    '# ================================================================',
    '# 5. BBR + Network Tuning',
    '# ================================================================',
    ..._bbr(bbr, isLinux),
    '',
    '# ================================================================',
    '# 6. System Tuning',
    '# ================================================================',
    ..._sysTune({ isLinux, isFreeBSD }),
    '',
    '# ================================================================',
    '# 7. Reinstall (optional)',
    '# ================================================================',
    'if [ "$REINSTALL" = 1 ]; then',
    '  echo "⚠  REINSTALL: stopping Nomad and purging data"',
    '  if [ "$IS_LINUX" = 1 ]; then',
    '    systemctl stop nomad 2>/dev/null || true',
    '  else',
    '    service nomad stop 2>/dev/null || true',
    '  fi',
    '  rm -rf /opt/nomad/data /etc/nomad.d',
    '  echo "✓ Data purged"',
    'fi',
    '',
    '# ================================================================',
    '# 8. Install Nomad',
    '# ================================================================',
    'if command -v nomad >/dev/null 2>&1; then',
    '  echo "✓ Nomad: $(nomad version | head -1)"',
    'else',
    '  echo "→ Installing Nomad..."',
    '  if [ "$IS_LINUX" = 1 ]; then',
    `    NOMAD_VER="1.9.6"`,
    `    ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')`,
    `    curl -fsSL "https://releases.hashicorp.com/nomad/\${NOMAD_VER}/nomad_\${NOMAD_VER}_linux_\${ARCH}.zip" -o /tmp/nomad.zip`,
    `    unzip -o /tmp/nomad.zip -d /usr/local/bin/`,
    `    chmod +x /usr/local/bin/nomad`,
    `    rm -f /tmp/nomad.zip`,
    '  else',
    '    pkg install -y nomad',
    '  fi',
    '  echo "✓ Nomad installed"',
    'fi',
    '',
    'mkdir -p /opt/nomad/data /etc/nomad.d',
    '',
    '# ================================================================',
    '# 9. Nomad Config',
    '# ================================================================',
    `cat > /etc/nomad.d/server.hcl << 'NMD'`,
    `datacenter = "${dc}"`,
    `name       = "${node.name}"`,
    `data_dir   = "/opt/nomad"`,
    ``,
    `server {`,
    `  enabled          = true`,
    `  bootstrap_expect = 1`,
    `  encrypt          = "GOSSIP_KEY_PLACEHOLDER"`,
    `}`,
    ``,
    `client {`,
    `  enabled = true`,
    `  options { "driver.raw_exec.enable" = "1" }`,
    `}`,
    ``,
    `plugin "pot" { config { enabled = true } }`,
    `NMD`,
    '',
    '# ---- ACL ----',
    `cat > /etc/nomad.d/acl.hcl << 'NMD'`,
    `acl { enabled = true }`,
    `NMD`,
    '',
    '# ---- Inject key ----',
    `sed -i "s/GOSSIP_KEY_PLACEHOLDER/\${GOSSIP_KEY}/" /etc/nomad.d/server.hcl`,
    '',
    '# ================================================================',
    '# 10. Start Nomad',
    '# ================================================================',
    'if [ "$IS_LINUX" = 1 ]; then',
    `  cat > /etc/systemd/system/nomad.service << 'UNIT'`,
    `[Unit]`,
    `Description=Nomad`,
    `After=network.target`,
    `[Service]`,
    `ExecStart=/usr/local/bin/nomad agent -config=/etc/nomad.d`,
    `Restart=on-failure`,
    `[Install]`,
    `WantedBy=multi-user.target`,
    `UNIT`,
    '  systemctl daemon-reload',
    '  systemctl enable nomad',
    '  systemctl restart nomad || systemctl start nomad',
    'else',
    '  sysrc nomad_enable=YES',
    '  sysrc nomad_args="-config=/etc/nomad.d"',
    '  service nomad status >/dev/null 2>&1 && service nomad restart || service nomad start',
    'fi',
    '',
    '# ================================================================',
    '# 11. Wait for Nomad + ACL Bootstrap',
    '# ================================================================',
    'echo "→ Waiting for Nomad..."',
    'for i in $(seq 1 30); do',
    '  nomad server members 2>/dev/null | grep -q alive && break',
    '  sleep 1',
    'done',
    '',
    'echo "→ Bootstrapping ACL..."',
    'MGMT_TOKEN=$(nomad acl bootstrap -json 2>/dev/null | grep -o \'"SecretID":"[^"]*"\' | head -1 | cut -d\'"\' -f4)',
    'if [ -n "$MGMT_TOKEN" ]; then',
    '  echo "✓ Management Token: $MGMT_TOKEN"',
    '  echo "NOMAD MANAGEMENT TOKEN: $MGMT_TOKEN"',
    'else',
    '  echo "⚠  ACL may already be bootstrapped (or Nomad not ready)"',
    'fi',
    '',
    '# ================================================================',
    '# 12. Deploy Jobs (Kanidm + Nginx)',
    '# ================================================================',
    'if [ -n "$MGMT_TOKEN" ]; then',
    '  export NOMAD_TOKEN="$MGMT_TOKEN"',
    '  export NOMAD_ADDR="http://127.0.0.1:4646"',
    `  cat > /tmp/kanidm.hcl << 'KJOB'`,
    kanidmHcl,
    `  KJOB`,
    `  cat > /tmp/nginx.hcl << 'NJOB'`,
    nginxHcl,
    `  NJOB`,
    '  echo "→ Submitting kanidm..."',
    '  nomad job run /tmp/kanidm.hcl 2>/dev/null || echo "⚠  kanidm submit failed"',
    '  echo "→ Submitting nginx..."',
    '  nomad job run /tmp/nginx.hcl 2>/dev/null || echo "⚠  nginx submit failed"',
    '  rm -f /tmp/kanidm.hcl /tmp/nginx.hcl',
    'fi',
    '',
    `echo "✓ Bootstrap complete — ${node.name} ready"`,
  ]);
}

// ---- Network setup ----
function _netSetup(isLinux, isStatic, nip) {
  if (!isStatic) return [
    `echo "✓ Network: DHCP (no static config)"`,
  ];

  // Static IP: extract gateway from IP (assume .1)
  const gw = nip.replace(/\.\d+$/, '.1');

  if (isLinux) {
    const iface = '$(ip route | grep default | awk \'{print $5}\' | head -1)';
    return [
      `echo "→ Setting static IP: ${nip}"`,
      `IFACE=${iface}`,
      `[ -z "$IFACE" ] && { echo "WARN: cannot detect interface, skipping static IP"; } || {`,
      `  ip addr add ${nip}/24 dev $IFACE 2>/dev/null || true`,
      `  ip route add default via ${gw} 2>/dev/null || true`,
      `  echo "✓ Static IP: ${nip}/24 on $IFACE"`,
      `}`,
    ];
  } else {
    return [
      `echo "→ Setting static IP: ${nip}"`,
      `IFACE=$(ifconfig -l ether 2>/dev/null | awk '{print $1}')`,
      `if [ -n "$IFACE" ]; then`,
      `  sysrc ifconfig_\${IFACE}="inet ${nip} netmask 255.255.255.0"`,
      `  sysrc defaultrouter="${gw}"`,
      `  service netif restart 2>/dev/null || true`,
      `  echo "✓ Static IP: ${nip}/24 on $IFACE"`,
      `fi`,
    ];
  }
}

// ---- BBR + net tuning ----
function _bbr(enabled, isLinux) {
  if (!enabled) return ['echo "ℹ  BBR: skipped"'];
  return [
    'echo "→ Enabling BBR..."',
    isLinux
      ? `modprobe tcp_bbr 2>/dev/null || true
sysctl -w net.core.default_qdisc=fq 2>/dev/null || true
sysctl -w net.ipv4.tcp_congestion_control=bbr 2>/dev/null || true
CONG=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null) && echo "✓ TCP congestion: \$CONG" || echo "⚠  BBR may not be available"`.split('\n').join('\n')
      : `sysctl net.inet.tcp.cc.algorithm=cubic 2>/dev/null || true
kldload tcp_bbr 2>/dev/null || true
sysctl net.inet.tcp.cc.algorithm=bbr 2>/dev/null && echo "✓ BBR enabled" || echo "ℹ  BBR: module not available on this kernel"`.split('\n').join('\n'),
  ];
}

// ---- System tuning ----
function _sysTune({ isLinux, isFreeBSD }) {
  const lines = [
    'echo "→ Applying system tuning..."',
  ];

  if (isLinux) {
    lines.push(
      'sysctl -w vm.swappiness=1 2>/dev/null || true',
      'sysctl -w vm.vfs_cache_pressure=50 2>/dev/null || true',
      'sysctl -w net.core.somaxconn=65535 2>/dev/null || true',
      'sysctl -w net.ipv4.tcp_max_syn_backlog=8192 2>/dev/null || true',
      'sysctl -w net.ipv4.ip_local_port_range="1024 65535" 2>/dev/null || true',
      'sysctl -w net.ipv4.tcp_tw_reuse=1 2>/dev/null || true',
      'sysctl -w fs.file-max=2097152 2>/dev/null || true',
      '# Persist',
      'cat > /etc/sysctl.d/99-anvil.conf << \'EOF\'',
      'vm.swappiness=1',
      'vm.vfs_cache_pressure=50',
      'net.core.somaxconn=65535',
      'net.ipv4.tcp_max_syn_backlog=8192',
      'net.ipv4.ip_local_port_range=1024 65535',
      'net.ipv4.tcp_tw_reuse=1',
      'fs.file-max=2097152',
      'EOF',
    );
  } else {
    lines.push(
      'sysctl kern.maxfiles=2097152 2>/dev/null || true',
      'sysctl net.inet.tcp.syncache.hashsize=1024 2>/dev/null || true',
      'sysctl net.inet.tcp.syncache.bucketlimit=100 2>/dev/null || true',
      'cat >> /etc/sysctl.conf << \'EOF\'',
      'kern.maxfiles=2097152',
      'EOF',
    );
  }

  lines.push(
    'echo "✓ System tuning applied"',
  );
  return lines;
}

function _lines(a) { return a.join('\n'); }
