// gen-client.mjs — Non-seed node: bare metal → join cluster
// Template: {NAME} {ROLE} {DC} etc

const $ = String.fromCharCode(36);

const SCRIPT = `#!/usr/bin/env bash
# ============================================================================
#  Nomad Bootstrap — {NAME} ({ROLE})
#  OS: {OS}  Net: {NET}  BBR: {BBR}  TZ: {TZ}
#  Generated by anvil CI — DO NOT EDIT
# ============================================================================
#
#  Usage:  curl .../{NAME}.sh | bash -s -- --gossip-key <key> --seed-addr <ip> [flags]
#  Flags:  --auto  --reinstall  --nomad-ver <x.y.z>
#          --skip-hostname  --skip-tz  --skip-net  --skip-bbr  --skip-tune
#          --skip-ssh  --skip-firewall  --skip-update
#  Env:    NOMAD_VER  NODE_HOSTNAME  NODE_TZ  NODE_IP  SEED_ADDR
# ============================================================================

set -euo pipefail

:{D}{NOMAD_VER:=1.9.6}
:{D}{NODE_HOSTNAME:={HN}}
:{D}{NODE_TZ:={TZ}}
:{D}{NODE_IP:={NIP}}

AUTO=0; REINSTALL=0; GOSSIP_KEY=""; SEED_ADDR=""
SKIP_HOSTNAME=0; SKIP_TZ=0; SKIP_NET=0; SKIP_BBR=0; SKIP_TUNE=0
SKIP_SSH=0; SKIP_FIREWALL=0; SKIP_UPDATE=0
while [[ $# -gt 0 ]]; do
  case "{D}1" in
    --gossip-key)   GOSSIP_KEY="{D}2"; shift 2 ;;
    --seed-addr)    SEED_ADDR="{D}2";  shift 2 ;;
    --auto)         AUTO=1; shift ;;
    --reinstall)    REINSTALL=1; shift ;;
    --nomad-ver)    NOMAD_VER="{D}2"; shift 2 ;;
    --skip-hostname) SKIP_HOSTNAME=1; shift ;;
    --skip-tz)       SKIP_TZ=1; shift ;;
    --skip-net)      SKIP_NET=1; shift ;;
    --skip-bbr)      SKIP_BBR=1; shift ;;
    --skip-tune)     SKIP_TUNE=1; shift ;;
    --skip-ssh)      SKIP_SSH=1; shift ;;
    --skip-firewall) SKIP_FIREWALL=1; shift ;;
    --skip-update)   SKIP_UPDATE=1; shift ;;
    -h|--help) sed -n '3,/^$/p' "{D}0" | head -18; exit 0 ;;
    *) echo "Unknown: {D}1  (try --help)"; exit 1 ;;
  esac
done
[[ -z "{D}GOSSIP_KEY" ]] && { echo "ERROR: --gossip-key required"; exit 1; }
[[ -z "{D}SEED_ADDR"  ]] && { echo "ERROR: --seed-addr required"; exit 1; }

RED='\\033[31m'; GREEN='\\033[32m'; YELLOW='\\033[33m'
CYAN='\\033[36m'; BOLD='\\033[1m'; RST='\\033[0m'; STEP=0
log()   { printf "  %s\\n" "{D}*"; }
ok()    { printf "{D}{GREEN}✓{D}{RST} %s\\n" "{D}*"; }
warn()  { printf "{D}{YELLOW}⚠{D}{RST} %s\\n" "{D}*" >&2; }
fail()  { printf "{D}{RED}✗{D}{RST} %s\\n" "{D}*" >&2; }
banner(){ printf "\\n{D}{CYAN}{D}{BOLD}── Step %s/{D}{TOTAL:-?}: %s{D}{RST}\\n" "$((++STEP))" "{D}*"; }
TOTAL=10
confirm() {
  [[ {D}AUTO -eq 1 ]] && return 0
  read -r -p "      {D}{1:-Continue? [Y/n]} " ans
  [[ "{D}ans" =~ ^[Nn] ]] && return 1
  return 0
}
trap 'fail "Bootstrap failed at line {D}LINENO"; exit 1' ERR

# ==================================================================
#  1. OS Detect
# ==================================================================
banner "OS Detect"
if [[ -f /etc/os-release ]]; then
  . /etc/os-release; ok "OS: {D}PRETTY_NAME"; IS_LINUX=1
  if command -v apt-get &>/dev/null; then PKG_MGR="apt-get"
  elif command -v dnf &>/dev/null; then PKG_MGR="dnf"
  elif command -v yum &>/dev/null; then PKG_MGR="yum"
  elif command -v apk &>/dev/null; then PKG_MGR="apk"
  else warn "no known package manager"; fi
elif [[ "{D}(uname -s)" == "FreeBSD" ]]; then
  ok "OS: FreeBSD {D}(freebsd-version 2>/dev/null || uname -r)"; IS_LINUX=0; PKG_MGR="pkg"
else fail "unsupported OS"; exit 1
fi

# ==================================================================
#  2. System Update
# ==================================================================
banner "System Update"
if [[ {D}SKIP_UPDATE -eq 1 ]]; then warn "skipped"
elif confirm "Update system packages? [Y/n]"; then
  if [[ {D}IS_LINUX -eq 1 ]]; then
    case "{D}PKG_MGR" in
      apt-get) apt-get update -qq && apt-get upgrade -y -qq ;;
      dnf|yum) {D}PKG_MGR update -y -q ;;
      apk) apk update && apk upgrade ;;
    esac
  else pkg update -q && pkg upgrade -y -q; fi
  ok "updated"
else warn "skipped by user"; fi

# ==================================================================
#  3. Hostname
# ==================================================================
banner "Hostname"
if [[ {D}SKIP_HOSTNAME -eq 1 ]]; then warn "skipped"
else
  if [[ {D}AUTO -eq 0 ]]; then
    read -r -p "      Hostname [{D}NODE_HOSTNAME]: " input
    [[ -n "{D}input" ]] && NODE_HOSTNAME="{D}input"
  fi
  if [[ {D}IS_LINUX -eq 1 ]]; then hostnamectl set-hostname "{D}NODE_HOSTNAME" 2>/dev/null || hostname "{D}NODE_HOSTNAME"
  else sysrc hostname="{D}NODE_HOSTNAME" 2>/dev/null || true; hostname "{D}NODE_HOSTNAME"; fi
  ok "{D}(hostname)"
fi

# ==================================================================
#  4. Timezone
# ==================================================================
banner "Timezone"
if [[ {D}SKIP_TZ -eq 1 ]]; then warn "skipped"
else
  if [[ {D}AUTO -eq 0 ]]; then
    read -r -p "      Timezone [{D}NODE_TZ]: " input
    [[ -n "{D}input" ]] && NODE_TZ="{D}input"
  fi
  if [[ {D}IS_LINUX -eq 1 ]]; then timedatectl set-timezone "{D}NODE_TZ" 2>/dev/null || true
  else tzsetup "{D}NODE_TZ" 2>/dev/null || true; fi
  ok "{D}NODE_TZ"
fi

# ==================================================================
#  5. Network
# ==================================================================
banner "Network"
if [[ {D}SKIP_NET -eq 1 ]]; then warn "skipped"
#NETHERE#
fi

# ==================================================================
#  6. BBR
# ==================================================================
banner "BBR"
if [[ {D}SKIP_BBR -eq 1 ]]; then warn "skipped"
elif confirm "Enable TCP BBR? [Y/n]"; then
  if [[ {D}IS_LINUX -eq 1 ]]; then
    modprobe tcp_bbr 2>/dev/null || true
    sysctl -w net.core.default_qdisc=fq 2>/dev/null || true
    sysctl -w net.ipv4.tcp_congestion_control=bbr 2>/dev/null || true
    echo "net.core.default_qdisc=fq" > /etc/sysctl.d/90-bbr.conf
    echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.d/90-bbr.conf
    local cc={D}(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null) && ok "{D}cc" || warn "BBR unavailable"
  else kldload tcp_bbr 2>/dev/null || true
    sysctl net.inet.tcp.cc.algorithm=bbr 2>/dev/null && ok "BBR" || warn "BBR unavailable"; fi
else warn "BBR skipped"; fi

# ==================================================================
#  7. System Tuning
# ==================================================================
banner "System Tuning"
if [[ {D}SKIP_TUNE -eq 1 ]]; then warn "skipped"
elif confirm "Apply system tuning? [Y/n]"; then
  if [[ {D}IS_LINUX -eq 1 ]]; then
    sysctl -w vm.swappiness=1 2>/dev/null || true; sysctl -w vm.vfs_cache_pressure=50 2>/dev/null || true
    sysctl -w net.core.somaxconn=65535 2>/dev/null || true; sysctl -w net.ipv4.tcp_max_syn_backlog=8192 2>/dev/null || true
    sysctl -w net.ipv4.ip_local_port_range="1024 65535" 2>/dev/null || true; sysctl -w net.ipv4.tcp_tw_reuse=1 2>/dev/null || true
    sysctl -w fs.file-max=2097152 2>/dev/null || true
    cat > /etc/sysctl.d/99-anvil.conf << 'EOF'
vm.swappiness=1
vm.vfs_cache_pressure=50
net.core.somaxconn=65535
net.ipv4.tcp_max_syn_backlog=8192
net.ipv4.ip_local_port_range=1024 65535
net.ipv4.tcp_tw_reuse=1
fs.file-max=2097152
EOF
  else sysctl kern.maxfiles=2097152 2>/dev/null || true; echo "kern.maxfiles=2097152" >> /etc/sysctl.conf; fi
  ok "tuning applied"
else warn "tuning skipped"; fi

# ==================================================================
#  8. SSH + Firewall
# ==================================================================
banner "SSH + Firewall"
if [[ {D}SKIP_SSH -ne 1 ]] && confirm "SSH hardening? [Y/n]"; then
  cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak.{D}(date +%s) 2>/dev/null || true
  sed -i -E 's/^#?(PermitRootLogin|PasswordAuthentication|PubkeyAuthentication|PermitEmptyPasswords|X11Forwarding).*/# removed by anvil/' /etc/ssh/sshd_config 2>/dev/null || true
  cat >> /etc/ssh/sshd_config << 'EOF'
PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes
PermitEmptyPasswords no
X11Forwarding no
EOF
  if [[ {D}IS_LINUX -eq 1 ]]; then systemctl reload sshd 2>/dev/null || true
  else service sshd reload 2>/dev/null || true; fi
  ok "SSH hardened"
fi
if [[ {D}SKIP_FIREWALL -ne 1 ]] && confirm "Firewall? [Y/n]"; then
  if [[ {D}IS_LINUX -eq 1 ]] && command -v nft &>/dev/null; then
    nft add table inet anvil 2>/dev/null || true
    nft add chain inet anvil input '{ type filter hook input priority 0; }' 2>/dev/null || true
    nft add rule inet anvil input ct state established,related accept 2>/dev/null || true
    nft add rule inet anvil input iif lo accept 2>/dev/null || true
    nft add rule inet anvil input tcp dport 22 accept 2>/dev/null || true
    nft add rule inet anvil input tcp dport '{4646,4647,4648}' accept 2>/dev/null || true
    nft add rule inet anvil input drop 2>/dev/null || true
    nft list ruleset > /etc/nftables.conf 2>/dev/null || true; ok "nftables"
  elif [[ {D}IS_LINUX -eq 0 ]]; then
    pfctl -e 2>/dev/null; ok "pf"
  else warn "no firewall configured"; fi
fi

# ==================================================================
#  9. Reinstall / Install
# ==================================================================
if [[ {D}REINSTALL -eq 1 ]]; then
  banner "Reinstall"
  if confirm "⚠  DESTROY existing Nomad data? [y/N]"; then
    if [[ {D}IS_LINUX -eq 1 ]]; then systemctl stop nomad 2>/dev/null || true
    else service nomad stop 2>/dev/null || true; fi
    rm -rf /opt/nomad/data /etc/nomad.d; ok "purged"
  else warn "cancelled"; exit 0; fi
fi
banner "Install Nomad"
if command -v nomad &>/dev/null && [[ {D}REINSTALL -ne 1 ]]; then
  ok "Nomad: {D}(nomad version | head -1)"
else
  log "installing Nomad v{D}NOMAD_VER ..."
  if [[ {D}IS_LINUX -eq 1 ]]; then
    local arch={D}(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
    curl -fsSL "https://releases.hashicorp.com/nomad/{D}NOMAD_VER/nomad_{D}NOMAD_VER_linux_{D}arch.zip" -o /tmp/nomad.zip
    unzip -o /tmp/nomad.zip -d /usr/local/bin/; chmod +x /usr/local/bin/nomad; rm -f /tmp/nomad.zip
  else pkg install -y nomad; fi
  ok "Nomad {D}(nomad version | head -1)"
fi
mkdir -p /opt/nomad/data /etc/nomad.d

# ==================================================================
#  10. Config + Start
# ==================================================================
banner "Nomad Config"
#JOINBLOCK#
sed -i "s/GOSSIP_KEY_PLACEHOLDER/{D}GOSSIP_KEY/" /etc/nomad.d/{ROLE}.hcl
sed -i "s/SEED_ADDR_PLACEHOLDER:4648/{D}SEED_ADDR:4648/" /etc/nomad.d/{ROLE}.hcl
ok "config written"

banner "Start Nomad"
if [[ {D}IS_LINUX -eq 1 ]]; then
  cat > /etc/systemd/system/nomad.service << 'UNIT'
[Unit]
Description=Nomad
After=network.target
[Service]
Type=simple
ExecStart=/usr/local/bin/nomad agent -config=/etc/nomad.d
Restart=on-failure
RestartSec=5
LimitNOFILE=65536
[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload && systemctl enable nomad
  systemctl restart nomad 2>/dev/null || systemctl start nomad
else
  sysrc nomad_enable=YES; sysrc nomad_args="-config=/etc/nomad.d"
  service nomad restart 2>/dev/null || service nomad start
fi

echo -n "→ Waiting "
for i in {D}(seq 1 60); do echo -n "."; nomad server members 2>/dev/null | grep -q alive && break; sleep 1; done
echo ""; ok "joined cluster"

echo ""
echo "╔══════════════════════════════════════════╗"
printf "║  %-40s ║\\n" "✓ {NAME} ready"
echo "╚══════════════════════════════════════════╝"`;

export function generate(node, cluster) {
  const net = node.network || 'dhcp';
  const isLinux = (node.os || 'linux') === 'linux';
  const isServer = node.role === 'server';
  const nip = node.ip || 'NODE_IP_PLACEHOLDER';
  const dc = cluster?.datacenter || 'dc1';

  // Network block
  let netBlock;
  if (net !== 'static') {
    netBlock = '  ok "DHCP — using existing configuration"';
  } else if (isLinux) {
    const gw = nip.replace(/\.\d+$/, '.1');
    netBlock = `  IFACE=\$(\$(ip -o link show | awk -F': ' '/state UP/ && !/lo/{print $2; exit}'))
  if [[ -n "{D}IFACE" ]]; then
    if [[ {D}AUTO -eq 0 ]]; then read -r -p "      IP/CIDR [{D}NODE_IP/24]: " input; [[ -n "{D}input" ]] && NODE_IP="{D}input"; fi
    ip addr add {D}NODE_IP/24 dev {D}IFACE 2>/dev/null || true
    ip route add default via ${gw} 2>/dev/null || true
    ok "{D}NODE_IP/24 on {D}IFACE"
  else warn "no active UP interface"; fi`;
  } else {
    netBlock = `  IFACE=\$(\$(ifconfig -l ether 2>/dev/null | awk '{print $1}'))
  if [[ -n "{D}IFACE" ]]; then
    if [[ {D}AUTO -eq 0 ]]; then read -r -p "      IP [{D}NODE_IP]: " input; [[ -n "{D}input" ]] && NODE_IP="{D}input"; fi
    sysrc ifconfig_{D}IFACE="inet {D}NODE_IP netmask 255.255.255.0"
    sysrc defaultrouter="{D}(echo {D}NODE_IP | sed 's/.[0-9]*$/.1/')"
    service netif restart 2>/dev/null || true
    ok "{D}NODE_IP/24 on {D}IFACE"; fi`;
  }

  // Join block
  const joinBlock = isServer
    ? `cat > /etc/nomad.d/server.hcl << 'NMD'
datacenter = "${dc}"
name       = "${node.name}"
data_dir   = "/opt/nomad"

server {
  enabled    = true
  retry_join = ["SEED_ADDR_PLACEHOLDER:4648"]
  encrypt    = "GOSSIP_KEY_PLACEHOLDER"
}

client {
  enabled = true
  options { "driver.raw_exec.enable" = "1" }
}
NMD`
    : `cat > /etc/nomad.d/client.hcl << 'NMD'
datacenter = "${dc}"
name       = "${node.name}"
data_dir   = "/opt/nomad"

client {
  enabled = true
  options { "driver.raw_exec.enable" = "1" }
  server_join { retry_join = ["SEED_ADDR_PLACEHOLDER:4648"] }
}
NMD`;

  let out = SCRIPT
    .replace('#NETHERE#', netBlock)
    .replace('#JOINBLOCK#', joinBlock);

  return out
    .replace(/\{NAME\}/g, node.name)
    .replace(/\{ROLE\}/g, node.role || 'client')
    .replace(/\{DC\}/g, dc)
    .replace(/\{HN\}/g, node.hostname || node.name)
    .replace(/\{TZ\}/g, node.timezone || 'UTC')
    .replace(/\{OS\}/g, node.os || 'linux')
    .replace(/\{NET\}/g, net)
    .replace(/\{BBR\}/g, node.bbr !== false ? 'true' : 'false')
    .replace(/\{NIP\}/g, nip)
    .replace(/\{D\}/g, $);
}
