// gen-client.mjs — Non-seed node: FreeBSD → join existing cluster
// Template: {NAME} {ROLE} {DC} etc

const $ = String.fromCharCode(36);

const SCRIPT = `#!/usr/bin/env bash
# ============================================================================
#  Nomad Bootstrap — {NAME} ({ROLE})
#  OS: FreeBSD  Net: {NET}  BBR: {BBR}  TZ: UTC
#  Generated by anvil CI — DO NOT EDIT
# ============================================================================
#
#  Usage:  curl .../{NAME}.sh | bash -s -- --gossip-key <key> --seed-addr <ip> [flags]
#  Flags:  --auto  --reinstall  --nomad-ver <x.y.z>
#          --skip-hostname  --skip-tz  --skip-net  --skip-bbr  --skip-tune
#          --skip-ssh  --skip-firewall  --skip-update
#  Env:    NOMAD_VER  NODE_HOSTNAME  NODE_TZ  NODE_IP  SEED_ADDR
# ============================================================================

set -euo pipefail

:{D}{NOMAD_VER:=1.9.6}
:{D}{NODE_HOSTNAME:={HN}}
:{D}{NODE_TZ:=UTC}
:{D}{NODE_IP:={NIP}}

AUTO=0; REINSTALL=0; GOSSIP_KEY=""; SEED_ADDR=""
SKIP_HOSTNAME=0; SKIP_TZ=0; SKIP_NET=0; SKIP_BBR=0; SKIP_TUNE=0
SKIP_SSH=0; SKIP_FIREWALL=0; SKIP_UPDATE=0
while [[ $# -gt 0 ]]; do
  case "{D}1" in
    --gossip-key)   GOSSIP_KEY="{D}2"; shift 2 ;;
    --seed-addr)    SEED_ADDR="{D}2";  shift 2 ;;
    --auto)         AUTO=1; shift ;;
    --reinstall)    REINSTALL=1; shift ;;
    --nomad-ver)    NOMAD_VER="{D}2"; shift 2 ;;
    --skip-hostname) SKIP_HOSTNAME=1; shift ;;
    --skip-tz)       SKIP_TZ=1; shift ;;
    --skip-net)      SKIP_NET=1; shift ;;
    --skip-bbr)      SKIP_BBR=1; shift ;;
    --skip-tune)     SKIP_TUNE=1; shift ;;
    --skip-ssh)      SKIP_SSH=1; shift ;;
    --skip-firewall) SKIP_FIREWALL=1; shift ;;
    --skip-update)   SKIP_UPDATE=1; shift ;;
    -h|--help) sed -n '3,/^$/p' "{D}0" | head -18; exit 0 ;;
    *) echo "Unknown: {D}1  (try --help)"; exit 1 ;;
  esac
done
[[ -z "{D}GOSSIP_KEY" ]] && { echo "ERROR: --gossip-key required"; exit 1; }
[[ -z "{D}SEED_ADDR"  ]] && { echo "ERROR: --seed-addr required"; exit 1; }

RED='\\033[31m'; GREEN='\\033[32m'; YELLOW='\\033[33m'
CYAN='\\033[36m'; BOLD='\\033[1m'; RST='\\033[0m'; STEP=0
log()   { printf "  %s\\n" "{D}*"; }
ok()    { printf "{D}{GREEN}✓{D}{RST} %s\\n" "{D}*"; }
warn()  { printf "{D}{YELLOW}⚠{D}{RST} %s\\n" "{D}*" >&2; }
fail()  { printf "{D}{RED}✗{D}{RST} %s\\n" "{D}*" >&2; }
banner(){ printf "\\n{D}{CYAN}{D}{BOLD}── Step %s/{D}{TOTAL:-?}: %s{D}{RST}\\n" "$((++STEP))" "{D}*"; }
TOTAL=10
confirm() {
  [[ {D}AUTO -eq 1 ]] && return 0
  read -r -p "      {D}{1:-Continue? [Y/n]} " ans
  [[ "{D}ans" =~ ^[Nn] ]] && return 1
  return 0
}
trap 'fail "Bootstrap failed at line {D}LINENO"; exit 1' ERR

# ==================================================================
#  1. OS
# ==================================================================
banner "OS"
ok "FreeBSD {D}(freebsd-version 2>/dev/null || uname -r)"

# ==================================================================
#  2. System Update
# ==================================================================
banner "System Update"
if [[ {D}SKIP_UPDATE -eq 1 ]]; then warn "skipped"
elif confirm "Update packages? [Y/n]"; then
  pkg update -q && pkg upgrade -y -q
  ok "packages updated"; fi

# ==================================================================
#  3. Hostname
# ==================================================================
banner "Hostname"
if [[ {D}SKIP_HOSTNAME -eq 1 ]]; then warn "skipped"
else
  if [[ {D}AUTO -eq 0 ]]; then
    read -r -p "      Hostname [{D}NODE_HOSTNAME]: " input
    [[ -n "{D}input" ]] && NODE_HOSTNAME="{D}input"
  fi
  log "setting: {D}NODE_HOSTNAME"
  sysrc hostname="{D}NODE_HOSTNAME" 2>/dev/null || true
  hostname "{D}NODE_HOSTNAME"
  ok "{D}(hostname)"
fi

# ==================================================================
#  4. Timezone + NTP (chrony)
# ==================================================================
banner "Timezone & NTP"
if [[ {D}SKIP_TZ -eq 1 ]]; then warn "skipped"
else
  log "setting UTC (cluster standard)"
  tzsetup UTC 2>/dev/null || true; ok "tz: UTC"
  log "installing chrony..."
  pkg install -y chrony >/dev/null 2>&1 || true
  cat > /usr/local/etc/chrony.conf <<'EOF'
server time.cloudflare.com iburst nts
server nts.netnod.se      iburst nts
pool   2.pool.ntp.org     iburst maxsources 2
driftfile /var/db/chrony/drift
makestep 1.0 3
rtcsync
rtconutc
port 0
EOF
  sysrc chronyd_enable=YES 2>/dev/null || true
  service chronyd restart 2>/dev/null || true
  sleep 2
  chronyc tracking 2>/dev/null | grep -q "Reference ID" && ok "chrony" || true
fi

# ==================================================================
#  5. Network
# ==================================================================
banner "Network"
if [[ {D}SKIP_NET -eq 1 ]]; then warn "skipped"
elif [[ "{D}NET}" != "static" ]]; then ok "DHCP — using existing configuration"
else
  IFACE={D}(\$(ifconfig -l ether 2>/dev/null | awk '{print $1}'))
  if [[ -n "{D}IFACE" ]]; then
    if [[ {D}AUTO -eq 0 ]]; then read -r -p "      IP [{D}NODE_IP]: " input; [[ -n "{D}input" ]] && NODE_IP="{D}input"; fi
    sysrc ifconfig_{D}IFACE="inet {D}NODE_IP netmask 255.255.255.0" 2>/dev/null || true
    service netif restart 2>/dev/null || true
    ok "{D}NODE_IP/24 on {D}IFACE"; fi
fi

# ==================================================================
#  6. DNS
# ==================================================================
banner "DNS"
grep nameserver /etc/resolv.conf 2>/dev/null | head -1 >/dev/null \
  && ok "DNS: {D}(grep nameserver /etc/resolv.conf | head -1)" \
  || warn "no DNS found"

# ==================================================================
#  7. BBR
# ==================================================================
banner "BBR"
if [[ {D}SKIP_BBR -eq 1 ]]; then warn "skipped"
else kldload tcp_bbr 2>/dev/null || true
  sysctl net.inet.tcp.cc.algorithm=bbr 2>/dev/null && ok "BBR" || true; fi

# ==================================================================
#  8. System Tuning
# ==================================================================
banner "System Tuning"
if [[ {D}SKIP_TUNE -eq 1 ]]; then warn "skipped"
elif confirm "Apply tuning? [Y/n]"; then
  sysctl kern.maxfiles=2097152 2>/dev/null || true
  echo "kern.maxfiles=2097152" >> /etc/sysctl.conf
  ok "tuning applied"; fi

# ==================================================================
#  9. SSH Hardening
# ==================================================================
banner "SSH Hardening"
if [[ {D}SKIP_SSH -eq 1 ]]; then warn "skipped"
elif confirm "Hardening? [Y/n]"; then
  CFG=/etc/ssh/sshd_config
  cp "{D}CFG" "{D}CFG.bak.{D}(date +%s)" 2>/dev/null || true
  cat >> "{D}CFG" <<'EOF'
PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes
PermitEmptyPasswords no
X11Forwarding no
EOF
  rm -f /etc/ssh/ssh_host_dsa_key* /etc/ssh/ssh_host_ecdsa_key* 2>/dev/null || true
  if sshd -t 2>/dev/null; then service sshd reload 2>/dev/null || true; ok "SSH hardened"
  else warn "SSH config invalid"; fi; fi

# ==================================================================
#  10. Install Nomad / Config / Start
# ==================================================================
if [[ {D}REINSTALL -eq 1 ]]; then
  banner "Reinstall"
  if confirm "⚠  DESTROY existing Nomad data? [y/N]"; then
    service nomad stop 2>/dev/null || true
    rm -rf /opt/nomad/data /etc/nomad.d
    ok "data purged"
  else warn "reinstall cancelled"; exit 0; fi; fi

banner "Install Nomad"
if command -v nomad >/dev/null 2>&1 && [[ {D}REINSTALL -ne 1 ]]; then
  ok "Nomad: {D}(nomad version | head -1)"
else
  pkg install -y nomad >/dev/null 2>&1 || fail "pkg install nomad failed"
  ok "Nomad {D}(nomad version | head -1)"; fi
mkdir -p /opt/nomad/data /etc/nomad.d

banner "Nomad Config"
cat > /etc/nomad.d/{ROLE}.hcl << 'NMD'
datacenter = "{DC}"
name       = "{NAME}"
data_dir   = "/opt/nomad"
{ROLE} {
  enabled = true
{ROLEBLOCK}
}
client {
  enabled = true
  options { "driver.raw_exec.enable" = "1" }
}
NMD
sed -i '' "s/GOSSIP_KEY_PLACEHOLDER/{D}GOSSIP_KEY/" /etc/nomad.d/{ROLE}.hcl
sed -i '' "s/SEED_ADDR_PLACEHOLDER:4648/{D}SEED_ADDR:4648/" /etc/nomad.d/{ROLE}.hcl
ok "config written"

banner "Start Nomad"
sysrc nomad_enable=YES
sysrc nomad_args="-config=/etc/nomad.d"
service nomad restart 2>/dev/null || service nomad start
echo -n "→ Joining "
for i in {D}(seq 1 60); do echo -n "."; sleep 1
  nomad server members 2>/dev/null | grep -q "{D}NODE_HOSTNAME" && break
done
echo ""; ok "{D}NODE_HOSTNAME joined"`;

// ---- Export ----
export function generate(node, cluster) {
  const net = node.network || 'dhcp';
  const nip = node.ip || 'NODE_IP_PLACEHOLDER';

  let roleBlock;
  if (node.role === 'client') {
    roleBlock = `  server_join { retry_join = ["SEED_ADDR_PLACEHOLDER:4648"] }`;
  } else {
    roleBlock = `  retry_join = ["SEED_ADDR_PLACEHOLDER:4648"]\n  encrypt    = "GOSSIP_KEY_PLACEHOLDER"`;
  }

  const dc = cluster?.datacenter || 'dc1';
  return SCRIPT
    .replace(/\{NAME\}/g, node.name)
    .replace(/\{ROLE\}/g, node.role)
    .replace(/\{ROLEBLOCK\}/g, roleBlock)
    .replace(/\{DC\}/g, dc)
    .replace(/\{HN\}/g, node.hostname || node.name)
    .replace(/\{TZ\}/g, 'UTC')
    .replace(/\{OS\}/g, 'freebsd')
    .replace(/\{NET\}/g, net)
    .replace(/\{BBR\}/g, node.bbr !== false ? 'true' : 'false')
    .replace(/\{NIP\}/g, nip)
    .replace(/\{D\}/g, $);
}
