// scripts/lib/gen-join.mjs
// 职责：生成通用集群加入脚本（server / client 角色）
// 输入：role ('server'|'client')
// 输出：参数化的 join 脚本
// 所有节点信息通过 env vars + CLI args 注入，零硬编码
// 与 gen-server/gen-client 不同：此脚本不内嵌任务，仅安装+加入

const $ = String.fromCharCode(36);

const JOIN_SERVER = `#!/usr/bin/env bash
# ============================================================================
#  anvil — Join as Nomad Server
#  Generated by anvil CI — DO NOT EDIT
# ============================================================================
#  Usage: curl .../join-server.sh | NODE_HOSTNAME=x NODE_TZ=x NODE_IP=x \\
#           sh -s -- --gossip-key <key> --seed-addr <ip> [--auto] [--reinstall]
#  Required:  --gossip-key, --seed-addr
# ============================================================================

set -euo pipefail

:{D}{NOMAD_VER:=1.9.6}
:{D}{NODE_HOSTNAME:=unknown}
:{D}{NODE_TZ:=UTC}
:{D}{NODE_IP:=}

AUTO=0; REINSTALL=0; GOSSIP_KEY=""; SEED_ADDR=""
while [[ $# -gt 0 ]]; do
  case "{D}1" in
    --gossip-key) GOSSIP_KEY="{D}2"; shift 2 ;;
    --seed-addr)  SEED_ADDR="{D}2";  shift 2 ;;
    --auto)       AUTO=1; shift ;;
    --reinstall)  REINSTALL=1; shift ;;
    --nomad-ver)  NOMAD_VER="{D}2"; shift 2 ;;
    *) echo "Unknown: {D}1"; exit 1 ;;
  esac
done
[[ -z "{D}GOSSIP_KEY" ]] && { echo "ERROR: --gossip-key required"; exit 1; }
[[ -z "{D}SEED_ADDR"  ]] && { echo "ERROR: --seed-addr required";  exit 1; }

R='\\033[31m'; G='\\033[32m'; Y='\\033[33m'; C='\\033[36m'; B='\\033[1m'; X='\\033[0m'
ok()   { printf "{D}{G}✓{D}{X} %s\\n" "{D}*"; }
warn() { printf "{D}{Y}⚠{D}{X} %s\\n" "{D}*" >&2; }
fail() { printf "{D}{R}✗{D}{X} %s\\n" "{D}*" >&2; exit 1; }

# ---- OS Detect ----
if [[ -f /etc/os-release ]]; then . /etc/os-release; IS_LINUX=1; PKG_MGR=""
  command -v apt-get &>/dev/null && PKG_MGR="apt-get"
  command -v dnf     &>/dev/null && PKG_MGR="dnf"
  command -v yum     &>/dev/null && PKG_MGR="yum"
elif [[ "{D}(uname -s)" == "FreeBSD" ]]; then IS_LINUX=0; PKG_MGR="pkg"
else fail "unsupported OS"; fi

# ---- Hostname ----
if [[ "{D}NODE_HOSTNAME" != "unknown" ]]; then
  if [[ {D}IS_LINUX -eq 1 ]]; then hostnamectl set-hostname "{D}NODE_HOSTNAME" 2>/dev/null || hostname "{D}NODE_HOSTNAME"
  else sysrc hostname="{D}NODE_HOSTNAME" 2>/dev/null || true; hostname "{D}NODE_HOSTNAME"; fi
  ok "hostname: {D}NODE_HOSTNAME"
fi

# ---- Timezone & NTP (chrony) ----
log "setting timezone: UTC (cluster standard)"
if [[ {D}IS_LINUX -eq 1 ]]; then timedatectl set-timezone UTC 2>/dev/null || true
else tzsetup UTC 2>/dev/null || true; fi
ok "tz: UTC"

log "installing chrony..."
if [[ {D}IS_LINUX -eq 1 ]]; then
  if command -v apt-get >/dev/null 2>&1; then {D}SUDO apt-get install -y chrony >/dev/null 2>&1 || true
  elif command -v dnf >/dev/null 2>&1; then {D}SUDO dnf install -y chrony >/dev/null 2>&1 || true
  elif command -v yum >/dev/null 2>&1; then {D}SUDO yum install -y chrony >/dev/null 2>&1 || true; fi
  cat > /etc/chrony/chrony.conf <<'CHRONYEOF'
pool 2.pool.ntp.org iburst
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
CHRONYEOF
  {D}SUDO systemctl enable chrony 2>/dev/null || {D}SUDO systemctl enable chronyd 2>/dev/null || true
  {D}SUDO systemctl restart chrony 2>/dev/null || {D}SUDO systemctl restart chronyd 2>/dev/null || true
  timedatectl set-ntp true 2>/dev/null || true
else
  pkg install -y chrony >/dev/null 2>&1 || true
  cat > /usr/local/etc/chrony.conf <<'CHRONYEOF'
pool 2.pool.ntp.org iburst
driftfile /var/db/chrony/drift
makestep 1.0 3
rtcsync
CHRONYEOF
  sysrc chronyd_enable=YES 2>/dev/null || true
  service chronyd restart 2>/dev/null || true
fi
ok "chrony NTP synced"

# ---- SSH Hardening ----
_ssh_harden() {
  local CFG=/etc/ssh/sshd_config
  if grep -q "^Include" "{D}CFG" 2>/dev/null && [[ -d /etc/ssh/sshd_config.d ]]; then
    CFG=/etc/ssh/sshd_config.d/99-anvil.conf
  fi
  cp "{D}CFG" "{D}CFG.bak.{D}(date +%s)" 2>/dev/null || true
  cat >> "{D}CFG" <<'SSHEOF'
PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes
PermitEmptyPasswords no
X11Forwarding no
SSHEOF
  rm -f /etc/ssh/ssh_host_dsa_key* /etc/ssh/ssh_host_ecdsa_key* 2>/dev/null || true
  if sshd -t 2>/dev/null; then
    if [[ {D}IS_LINUX -eq 1 ]]; then systemctl reload sshd 2>/dev/null || systemctl restart sshd 2>/dev/null || true
    else service sshd reload 2>/dev/null || service sshd restart 2>/dev/null || true; fi
    ok "SSH hardened"
  fi
}
_ssh_harden

# ---- Reinstall ----
[[ {D}REINSTALL -eq 1 ]] && {
  if [[ {D}IS_LINUX -eq 1 ]]; then systemctl stop nomad 2>/dev/null || true
  else service nomad stop 2>/dev/null || true; fi
  rm -rf /opt/nomad/data /etc/nomad.d
  ok "data purged"; }

# ---- Install Nomad ----
if command -v nomad &>/dev/null && [[ {D}REINSTALL -ne 1 ]]; then
  ok "Nomad: {D}(nomad version | head -1)"
else
  if [[ {D}IS_LINUX -eq 1 ]]; then
    local a; a={D}(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
    curl -fsSL "https://releases.hashicorp.com/nomad/{D}NOMAD_VER/nomad_{D}NOMAD_VER_linux_{D}a.zip" -o /tmp/n.zip
    unzip -o /tmp/n.zip -d /usr/local/bin/; chmod +x /usr/local/bin/nomad; rm -f /tmp/n.zip
  else pkg install -y nomad; fi
  ok "Nomad {D}(nomad version | head -1)"; fi
mkdir -p /opt/nomad/data /etc/nomad.d

# ---- Config ----
cat > /etc/nomad.d/server.hcl << 'NMD'
datacenter = "dc1"
name       = "GENERIC_PLACEHOLDER"
data_dir   = "/opt/nomad"
server {
  enabled    = true
  retry_join = ["SEED_ADDR_PLACEHOLDER:4648"]
  encrypt    = "GOSSIP_KEY_PLACEHOLDER"
}
client {
  enabled = true
  options { "driver.raw_exec.enable" = "1" }
}
NMD
sed -i "s/GENERIC_PLACEHOLDER/{D}NODE_HOSTNAME/" /etc/nomad.d/server.hcl
sed -i "s/GOSSIP_KEY_PLACEHOLDER/{D}GOSSIP_KEY/"    /etc/nomad.d/server.hcl
sed -i "s/SEED_ADDR_PLACEHOLDER:4648/{D}SEED_ADDR:4648/" /etc/nomad.d/server.hcl
ok "config: server → {D}SEED_ADDR"

# ---- Start ----
if [[ {D}IS_LINUX -eq 1 ]]; then
  cat > /etc/systemd/system/nomad.service << 'UNIT'
[Unit]
Description=Nomad
After=network.target
[Service]
Type=simple;ExecStart=/usr/local/bin/nomad agent -config=/etc/nomad.d
Restart=on-failure;RestartSec=5;LimitNOFILE=65536
[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload && systemctl enable nomad
  systemctl restart nomad 2>/dev/null || systemctl start nomad
else
  sysrc nomad_enable=YES; sysrc nomad_args="-config=/etc/nomad.d"
  service nomad restart 2>/dev/null || service nomad start
fi
echo -n "→ Joining "
for i in {D}(seq 1 60); do echo -n "."
  nomad server members 2>/dev/null | grep -q alive && break
  sleep 1
done
echo ""
if nomad server members 2>/dev/null | grep -q "{D}NODE_HOSTNAME}"; then
  ok "{D}NODE_HOSTNAME joined cluster"
else warn "{D}NODE_HOSTNAME may still be joining — check nomad server members"; fi
echo "✓ {D}NODE_HOSTNAME online"`;

const JOIN_CLIENT = `#!/usr/bin/env bash
# ============================================================================
#  anvil — Join as Nomad Client
#  Generated by anvil CI — DO NOT EDIT
# ============================================================================
#  Usage: curl .../join-client.sh | NODE_HOSTNAME=x NODE_TZ=x \\
#           sh -s -- --gossip-key <key> --seed-addr <ip> [--auto] [--reinstall]
#  Required:  --gossip-key, --seed-addr
# ============================================================================

set -euo pipefail

:{D}{NOMAD_VER:=1.9.6}
:{D}{NODE_HOSTNAME:=unknown}
:{D}{NODE_TZ:=UTC}

AUTO=0; REINSTALL=0; GOSSIP_KEY=""; SEED_ADDR=""
while [[ $# -gt 0 ]]; do
  case "{D}1" in
    --gossip-key) GOSSIP_KEY="{D}2"; shift 2 ;;
    --seed-addr)  SEED_ADDR="{D}2";  shift 2 ;;
    --auto)       AUTO=1; shift ;;
    --reinstall)  REINSTALL=1; shift ;;
    --nomad-ver)  NOMAD_VER="{D}2"; shift 2 ;;
    *) echo "Unknown: {D}1"; exit 1 ;;
  esac
done
[[ -z "{D}GOSSIP_KEY" ]] && { echo "ERROR: --gossip-key required"; exit 1; }
[[ -z "{D}SEED_ADDR"  ]] && { echo "ERROR: --seed-addr required";  exit 1; }

ok()   { printf "\\033[32m✓\\033[0m %s\\n" "{D}*"; }
fail() { printf "\\033[31m✗\\033[0m %s\\n" "{D}*" >&2; exit 1; }

if [[ -f /etc/os-release ]]; then . /etc/os-release; IS_LINUX=1
  command -v apt-get &>/dev/null && PKG_MGR="apt-get"
  command -v dnf     &>/dev/null && PKG_MGR="dnf"
elif [[ "{D}(uname -s)" == "FreeBSD" ]]; then IS_LINUX=0; PKG_MGR="pkg"
else fail "unsupported OS"; fi

[[ "{D}NODE_HOSTNAME" != "unknown" ]] && {
  if [[ {D}IS_LINUX -eq 1 ]]; then hostnamectl set-hostname "{D}NODE_HOSTNAME" 2>/dev/null || hostname "{D}NODE_HOSTNAME"
  else sysrc hostname="{D}NODE_HOSTNAME" 2>/dev/null || true; hostname "{D}NODE_HOSTNAME"; fi; }

# ---- Timezone & NTP (chrony) ----
log "setting timezone: UTC (cluster standard)"
if [[ {D}IS_LINUX -eq 1 ]]; then timedatectl set-timezone UTC 2>/dev/null || true
else tzsetup UTC 2>/dev/null || true; fi; ok "tz: UTC"
log "installing chrony..."
  if [[ {D}IS_LINUX -eq 1 ]]; then
    if command -v apt-get >/dev/null 2>&1; then {D}SUDO apt-get install -y chrony >/dev/null 2>&1 || true
    elif command -v dnf >/dev/null 2>&1; then {D}SUDO dnf install -y chrony >/dev/null 2>&1 || true
    elif command -v yum >/dev/null 2>&1; then {D}SUDO yum install -y chrony >/dev/null 2>&1 || true; fi
    cat > /etc/chrony/chrony.conf <<'CHRONYEOF'
pool 2.pool.ntp.org iburst
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
CHRONYEOF
    {D}SUDO systemctl enable chrony 2>/dev/null || {D}SUDO systemctl enable chronyd 2>/dev/null || true
    {D}SUDO systemctl restart chrony 2>/dev/null || {D}SUDO systemctl restart chronyd 2>/dev/null || true
    timedatectl set-ntp true 2>/dev/null || true
  else
    pkg install -y chrony >/dev/null 2>&1 || true
    cat > /usr/local/etc/chrony.conf <<'CHRONYEOF'
pool 2.pool.ntp.org iburst
driftfile /var/db/chrony/drift
makestep 1.0 3
rtcsync
CHRONYEOF
    sysrc chronyd_enable=YES 2>/dev/null || true
    service chronyd restart 2>/dev/null || true
  fi
  ok "chrony NTP synced"

# ---- SSH Hardening ----
_ssh_harden() {
  local CFG=/etc/ssh/sshd_config
  if grep -q "^Include" "{D}CFG" 2>/dev/null && [[ -d /etc/ssh/sshd_config.d ]]; then
    CFG=/etc/ssh/sshd_config.d/99-anvil.conf
  fi
  cp "{D}CFG" "{D}CFG.bak.{D}(date +%s)" 2>/dev/null || true
  cat >> "{D}CFG" <<'SSHEOF'
PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes
PermitEmptyPasswords no
X11Forwarding no
SSHEOF
  rm -f /etc/ssh/ssh_host_dsa_key* /etc/ssh/ssh_host_ecdsa_key* 2>/dev/null || true
  if sshd -t 2>/dev/null; then
    if [[ {D}IS_LINUX -eq 1 ]]; then systemctl reload sshd 2>/dev/null || systemctl restart sshd 2>/dev/null || true
    else service sshd reload 2>/dev/null || service sshd restart 2>/dev/null || true; fi
    ok "SSH hardened"
  fi
}
_ssh_harden

[[ {D}REINSTALL -eq 1 ]] && {
  if [[ {D}IS_LINUX -eq 1 ]]; then systemctl stop nomad 2>/dev/null || true
  else service nomad stop 2>/dev/null || true; fi
  rm -rf /opt/nomad/data /etc/nomad.d; }

if command -v nomad &>/dev/null && [[ {D}REINSTALL -ne 1 ]]; then
  ok "Nomad: {D}(nomad version | head -1)"
else
  if [[ {D}IS_LINUX -eq 1 ]]; then
    local a={D}(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
    curl -fsSL "https://releases.hashicorp.com/nomad/{D}NOMAD_VER/nomad_{D}NOMAD_VER_linux_{D}a.zip" -o /tmp/n.zip
    unzip -o /tmp/n.zip -d /usr/local/bin/; chmod +x /usr/local/bin/nomad; rm -f /tmp/n.zip
  else pkg install -y nomad; fi
  ok "Nomad {D}(nomad version | head -1)"; fi
mkdir -p /opt/nomad/data /etc/nomad.d

cat > /etc/nomad.d/client.hcl << 'NMD'
datacenter = "dc1"
name       = "GENERIC_PLACEHOLDER"
data_dir   = "/opt/nomad"
client {
  enabled = true
  options { "driver.raw_exec.enable" = "1" }
  server_join { retry_join = ["SEED_ADDR_PLACEHOLDER:4648"] }
}
NMD
sed -i "s/GENERIC_PLACEHOLDER/{D}NODE_HOSTNAME/" /etc/nomad.d/client.hcl
sed -i "s/SEED_ADDR_PLACEHOLDER:4648/{D}SEED_ADDR:4648/" /etc/nomad.d/client.hcl

if [[ {D}IS_LINUX -eq 1 ]]; then
  cat > /etc/systemd/system/nomad.service << 'UNIT'
[Unit]
Description=Nomad;After=network.target
[Service]
Type=simple;ExecStart=/usr/local/bin/nomad agent -config=/etc/nomad.d
Restart=on-failure;RestartSec=5;LimitNOFILE=65536
[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload && systemctl enable nomad
  systemctl restart nomad 2>/dev/null || systemctl start nomad
else
  sysrc nomad_enable=YES; sysrc nomad_args="-config=/etc/nomad.d"
  service nomad restart 2>/dev/null || service nomad start
fi
echo -n "→ Joining "
for i in {D}(seq 1 30); do echo -n "."; sleep 1
  nomad node status 2>/dev/null | grep -q "{D}NODE_HOSTNAME" && break
done
echo ""; ok "{D}NODE_HOSTNAME registered as client"`;

// ---- Export ----
export function generate(role) {
  const template = role === 'server' ? JOIN_SERVER : JOIN_CLIENT;
  return template.replace(/\{D\}/g, $);
}
